-- Mart-facing views for generic content v2.
--
-- APS_MART exposes app/reporting shapes. APS_CORE remains the normalized source of
-- truth and owns derivation rules.

CREATE SCHEMA IF NOT EXISTS APS_MART;

CREATE OR REPLACE VIEW APS_MART.INVESTMENT_NOTE_TIMELINE_FROM_CONTENT AS
SELECT
    INVESTMENT_NAME,
    PORTFOLIO_NAME,
    EFFECTIVE_DATE,
    SOURCE_TYPE,
    SOURCE_URL,
    SOURCE_SHAREPOINT,
    SOURCE_REFERENCE,
    SUMMARY,
    NOTE_TEXT,
    SOURCE_CONTENT_ID,
    SOURCE_CONTENT_VERSION_ID,
    SOURCE_ENTITY_LINK_ID,
    SOURCE_CONTENT_BODY_ID,
    INVESTMENT_ID,
    ENTITY_LINK_CONFIDENCE,
    ENTITY_LINK_REVIEW_STATUS,
    EFFECTIVE_DATE_SOURCE_TYPE,
    EFFECTIVE_DATE_CONFIDENCE,
    SOURCE_SECTION_PATH,
    SOURCE_SECTION_TITLE,
    DERIVATION_STATUS,
    DERIVATION_RULE_VERSION,
    VIEW_EVALUATED_AT
FROM APS_CORE.INVESTMENT_NOTES_FROM_CONTENT;

COMMENT ON VIEW APS_MART.INVESTMENT_NOTE_TIMELINE_FROM_CONTENT IS
    'App/reporting-facing investment note timeline derived from generic content.';

CREATE OR REPLACE VIEW APS_MART.PORTFOLIO_NOTE_TIMELINE_FROM_CONTENT AS
SELECT
    PORTFOLIO_ID,
    PORTFOLIO_NAME,
    PORTFOLIO_ENTITY_TYPE,
    EFFECTIVE_DATE,
    SOURCE_TYPE,
    SOURCE_URL,
    SOURCE_SHAREPOINT,
    SOURCE_REFERENCE,
    SUMMARY,
    NOTE_TEXT,
    SOURCE_CONTENT_ID,
    SOURCE_CONTENT_VERSION_ID,
    SOURCE_ENTITY_LINK_ID,
    SOURCE_CONTENT_BODY_ID,
    ENTITY_LINK_CONFIDENCE,
    ENTITY_LINK_REVIEW_STATUS,
    EFFECTIVE_DATE_SOURCE_TYPE,
    EFFECTIVE_DATE_CONFIDENCE,
    DERIVATION_STATUS,
    DERIVATION_RULE_VERSION,
    VIEW_EVALUATED_AT
FROM APS_CORE.PORTFOLIO_NOTES_FROM_CONTENT;

COMMENT ON VIEW APS_MART.PORTFOLIO_NOTE_TIMELINE_FROM_CONTENT IS
    'App/reporting-facing portfolio/fund note timeline derived from generic content.';

CREATE OR REPLACE VIEW APS_MART.STRATEGY_NOTE_TIMELINE_FROM_CONTENT AS
SELECT
    STRATEGY_ID,
    STRATEGY_NAME,
    STRATEGY_ENTITY_TYPE,
    EFFECTIVE_DATE,
    SOURCE_TYPE,
    SOURCE_URL,
    SOURCE_SHAREPOINT,
    SOURCE_REFERENCE,
    SUMMARY,
    NOTE_TEXT,
    SOURCE_CONTENT_ID,
    SOURCE_CONTENT_VERSION_ID,
    SOURCE_ENTITY_LINK_ID,
    SOURCE_CONTENT_BODY_ID,
    ENTITY_LINK_CONFIDENCE,
    ENTITY_LINK_REVIEW_STATUS,
    EFFECTIVE_DATE_SOURCE_TYPE,
    EFFECTIVE_DATE_CONFIDENCE,
    DERIVATION_STATUS,
    DERIVATION_RULE_VERSION,
    VIEW_EVALUATED_AT
FROM APS_CORE.STRATEGY_NOTES_FROM_CONTENT;

COMMENT ON VIEW APS_MART.STRATEGY_NOTE_TIMELINE_FROM_CONTENT IS
    'App/reporting-facing strategy/topic note timeline derived from generic content.';

CREATE OR REPLACE VIEW APS_MART.CONTENT_REVIEW_QUEUE AS
WITH issue_rollup AS (
    SELECT
        CONTENT_ID,
        LISTAGG(DISTINCT ISSUE_CODE, ', ') WITHIN GROUP (ORDER BY ISSUE_CODE) AS REVIEW_REASONS,
        MAX(CASE SEVERITY WHEN 'P1' THEN 3 WHEN 'P2' THEN 2 WHEN 'P3' THEN 1 ELSE 0 END) AS MAX_SEVERITY_RANK,
        COUNT(*) AS ISSUE_COUNT,
        COUNT_IF(SEVERITY = 'P1') AS P1_ISSUE_COUNT,
        COUNT_IF(SEVERITY = 'P2') AS P2_ISSUE_COUNT,
        COUNT_IF(SEVERITY = 'P3') AS P3_ISSUE_COUNT
    FROM APS_CORE.CONTENT_REVIEW_ISSUES
    GROUP BY CONTENT_ID
),
asset_health AS (
    SELECT
        ccv.CONTENT_ID,
        COUNT(ca.CONTENT_ASSET_ID) AS ASSET_COUNT,
        COUNT_IF(UPPER(ca.ASSET_TYPE) IN ('IMAGE', 'CHART', 'SCREENSHOT', 'TABLE_IMAGE')) AS IMAGE_LIKE_ASSET_COUNT,
        COUNT_IF(ca.OCR_TEXT IS NOT NULL OR ca.CAPTION_TEXT IS NOT NULL OR ca.CHART_DATA IS NOT NULL) AS ASSETS_WITH_EXTRACTED_CONTEXT
    FROM APS_CORE.CONTENT_CURRENT_VERSIONS ccv
    LEFT JOIN APS_CORE.CONTENT_ASSETS ca
        ON ca.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID
    GROUP BY ccv.CONTENT_ID
),
entity_health AS (
    SELECT
        ccv.CONTENT_ID,
        COUNT(cel.CONTENT_ENTITY_LINK_ID) AS ENTITY_LINK_COUNT,
        COUNT_IF(UPPER(cel.REVIEW_STATUS) IN ('AUTO_ACCEPTED', 'APPROVED', 'REJECTED')) AS REVIEWED_ENTITY_LINK_COUNT,
        COUNT_IF(cel.ENTITY_ID IS NULL AND cel.ENTITY_NAME IS NOT NULL) AS UNRESOLVED_ENTITY_MENTION_COUNT
    FROM APS_CORE.CONTENT_CURRENT_VERSIONS ccv
    LEFT JOIN APS_CORE.CONTENT_ENTITY_LINKS cel
        ON cel.CONTENT_ID = ccv.CONTENT_ID
       AND (cel.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID OR cel.CONTENT_VERSION_ID IS NULL)
    GROUP BY ccv.CONTENT_ID
)
SELECT
    ccv.CONTENT_ID,
    ccv.CONTENT_VERSION_ID,
    ccv.SOURCE_TITLE,
    ccv.SOURCE_SYSTEM,
    ccv.SOURCE_TYPE,
    ccv.SOURCE_URI,
    ccv.SOURCE_REFERENCE,
    ccv.CONTENT_REVIEW_STATUS,
    ccv.CONTENT_STATUS_REASON,
    CASE ir.MAX_SEVERITY_RANK
        WHEN 3 THEN 'P1'
        WHEN 2 THEN 'P2'
        WHEN 1 THEN 'P3'
        ELSE 'OK'
    END AS MAX_REVIEW_SEVERITY,
    COALESCE(ir.REVIEW_REASONS, 'OK') AS REVIEW_REASONS,
    COALESCE(ir.ISSUE_COUNT, 0) AS ISSUE_COUNT,
    COALESCE(ir.P1_ISSUE_COUNT, 0) AS P1_ISSUE_COUNT,
    COALESCE(ir.P2_ISSUE_COUNT, 0) AS P2_ISSUE_COUNT,
    COALESCE(ir.P3_ISSUE_COUNT, 0) AS P3_ISSUE_COUNT,
    COALESCE(eh.ENTITY_LINK_COUNT, 0) AS ENTITY_LINK_COUNT,
    COALESCE(eh.REVIEWED_ENTITY_LINK_COUNT, 0) AS REVIEWED_ENTITY_LINK_COUNT,
    COALESCE(eh.UNRESOLVED_ENTITY_MENTION_COUNT, 0) AS UNRESOLVED_ENTITY_MENTION_COUNT,
    COALESCE(ah.ASSET_COUNT, 0) AS ASSET_COUNT,
    COALESCE(ah.IMAGE_LIKE_ASSET_COUNT, 0) AS IMAGE_LIKE_ASSET_COUNT,
    COALESCE(ah.ASSETS_WITH_EXTRACTED_CONTEXT, 0) AS ASSETS_WITH_EXTRACTED_CONTEXT,
    ccv.CURRENT_VERSION_SELECTED_AT,
    ccv.CURRENT_VERSION_SELECTION_REASON
FROM APS_CORE.CONTENT_CURRENT_VERSIONS ccv
LEFT JOIN issue_rollup ir
    ON ir.CONTENT_ID = ccv.CONTENT_ID
LEFT JOIN asset_health ah
    ON ah.CONTENT_ID = ccv.CONTENT_ID
LEFT JOIN entity_health eh
    ON eh.CONTENT_ID = ccv.CONTENT_ID
WHERE COALESCE(ir.ISSUE_COUNT, 0) > 0
   OR UPPER(ccv.CONTENT_REVIEW_STATUS) IN ('NEEDS_REVIEW', 'UNREVIEWED');

COMMENT ON VIEW APS_MART.CONTENT_REVIEW_QUEUE IS
    'Review queue for ambiguous generic content, duplicate/current-version conflicts, missing anchors, missing reviewed links, undated notes, and image-heavy notes missing extracted context.';
