-- Mart-facing views for generic content.
--
-- These views keep application/reporting access out of the canonical intake tables.

CREATE SCHEMA IF NOT EXISTS APS_MART;

CREATE OR REPLACE VIEW APS_MART.INVESTMENT_NOTE_TIMELINE_FROM_CONTENT AS
SELECT
    INVESTMENT_NAME,
    PORTFOLIO_NAME,
    EFFECTIVE_DATE,
    SOURCE_TYPE,
    SOURCE_URL,
    SOURCE_REFERENCE,
    SUMMARY,
    NOTE_TEXT,
    SOURCE_CONTENT_ID,
    SOURCE_CONTENT_VERSION_ID,
    SOURCE_ENTITY_LINK_ID,
    INVESTMENT_ID,
    ENTITY_LINK_CONFIDENCE,
    EFFECTIVE_DATE_CONFIDENCE,
    DERIVATION_STATUS,
    DERIVATION_RULE_VERSION,
    VIEW_EVALUATED_AT
FROM APS_CORE.INVESTMENT_NOTES_FROM_CONTENT;

COMMENT ON VIEW APS_MART.INVESTMENT_NOTE_TIMELINE_FROM_CONTENT IS
    'App/reporting-facing investment note timeline derived from generic content.';

CREATE OR REPLACE VIEW APS_MART.CONTENT_REVIEW_QUEUE AS
WITH unresolved_links AS (
    SELECT
        CONTENT_ID,
        COUNT_IF(UPPER(REVIEW_STATUS) = 'NEEDS_REVIEW') AS ENTITY_LINKS_NEEDING_REVIEW,
        COUNT_IF(UPPER(ENTITY_TYPE) = 'INVESTMENT' AND COALESCE(CONFIDENCE, 0) < 0.85) AS LOW_CONFIDENCE_INVESTMENT_LINKS,
        COUNT_IF(ENTITY_ID IS NULL AND ENTITY_NAME IS NOT NULL) AS UNRESOLVED_ENTITY_MENTIONS
    FROM APS_CORE.CONTENT_ENTITY_LINKS
    GROUP BY CONTENT_ID
),
date_health AS (
    SELECT
        CONTENT_ID,
        COUNT(*) AS DATE_CANDIDATE_COUNT,
        COUNT_IF(IS_PRIMARY_CANDIDATE) AS PRIMARY_DATE_CANDIDATE_COUNT
    FROM APS_CORE.CONTENT_DATES
    GROUP BY CONTENT_ID
),
asset_health AS (
    SELECT
        cv.CONTENT_ID,
        COUNT(*) AS ASSET_COUNT,
        COUNT_IF(OCR_TEXT IS NOT NULL OR CAPTION_TEXT IS NOT NULL OR CHART_DATA IS NOT NULL) AS ASSETS_WITH_EXTRACTED_CONTEXT
    FROM APS_CORE.CONTENT_ASSETS ca
    JOIN APS_CORE.CONTENT_VERSIONS cv
        ON cv.CONTENT_VERSION_ID = ca.CONTENT_VERSION_ID
    GROUP BY cv.CONTENT_ID
)
SELECT
    ci.CONTENT_ID,
    ci.SOURCE_TITLE,
    ci.SOURCE_SYSTEM,
    ci.SOURCE_TYPE,
    ci.SOURCE_URI,
    ci.SOURCE_REFERENCE,
    ci.REVIEW_STATUS,
    ci.STATUS_REASON,
    COALESCE(ul.ENTITY_LINKS_NEEDING_REVIEW, 0) AS ENTITY_LINKS_NEEDING_REVIEW,
    COALESCE(ul.LOW_CONFIDENCE_INVESTMENT_LINKS, 0) AS LOW_CONFIDENCE_INVESTMENT_LINKS,
    COALESCE(ul.UNRESOLVED_ENTITY_MENTIONS, 0) AS UNRESOLVED_ENTITY_MENTIONS,
    COALESCE(dh.DATE_CANDIDATE_COUNT, 0) AS DATE_CANDIDATE_COUNT,
    COALESCE(dh.PRIMARY_DATE_CANDIDATE_COUNT, 0) AS PRIMARY_DATE_CANDIDATE_COUNT,
    COALESCE(ah.ASSET_COUNT, 0) AS ASSET_COUNT,
    COALESCE(ah.ASSETS_WITH_EXTRACTED_CONTEXT, 0) AS ASSETS_WITH_EXTRACTED_CONTEXT,
    CASE
        WHEN COALESCE(ul.ENTITY_LINKS_NEEDING_REVIEW, 0) > 0 THEN 'ENTITY_RESOLUTION'
        WHEN COALESCE(ul.LOW_CONFIDENCE_INVESTMENT_LINKS, 0) > 0 THEN 'LOW_CONFIDENCE_INVESTMENT_LINK'
        WHEN COALESCE(dh.DATE_CANDIDATE_COUNT, 0) = 0 THEN 'NO_DATE_CANDIDATES'
        WHEN COALESCE(ah.ASSET_COUNT, 0) > 0 AND COALESCE(ah.ASSETS_WITH_EXTRACTED_CONTEXT, 0) = 0 THEN 'IMAGE_CONTEXT_MISSING'
        WHEN UPPER(ci.REVIEW_STATUS) IN ('NEEDS_REVIEW', 'UNREVIEWED') THEN ci.REVIEW_STATUS
        ELSE 'OK'
    END AS REVIEW_REASON,
    ci.INGESTED_AT,
    ci.UPDATED_AT
FROM APS_CORE.CONTENT_ITEMS ci
LEFT JOIN unresolved_links ul
    ON ul.CONTENT_ID = ci.CONTENT_ID
LEFT JOIN date_health dh
    ON dh.CONTENT_ID = ci.CONTENT_ID
LEFT JOIN asset_health ah
    ON ah.CONTENT_ID = ci.CONTENT_ID
WHERE ci.IS_ACTIVE
  AND (
      UPPER(ci.REVIEW_STATUS) IN ('NEEDS_REVIEW', 'UNREVIEWED')
      OR COALESCE(ul.ENTITY_LINKS_NEEDING_REVIEW, 0) > 0
      OR COALESCE(ul.LOW_CONFIDENCE_INVESTMENT_LINKS, 0) > 0
      OR COALESCE(dh.DATE_CANDIDATE_COUNT, 0) = 0
      OR (COALESCE(ah.ASSET_COUNT, 0) > 0 AND COALESCE(ah.ASSETS_WITH_EXTRACTED_CONTEXT, 0) = 0)
  );

COMMENT ON VIEW APS_MART.CONTENT_REVIEW_QUEUE IS
    'Review queue for ambiguous generic content, including low-confidence entity links, undated notes, and image-heavy notes missing extracted context.';
