-- Pre-merge validation for the APS markdown-note adapter.
--
-- Expected session input:
--   SET STAGE_INGESTION_RUN_ID = '<ingestion-run-id>';

WITH
stage_items AS (
    SELECT *
    FROM APS_RAW.STAGE_CONTENT_ITEMS
    WHERE INGESTION_RUN_ID = $STAGE_INGESTION_RUN_ID
),
stage_versions AS (
    SELECT *
    FROM APS_RAW.STAGE_CONTENT_VERSIONS
    WHERE INGESTION_RUN_ID = $STAGE_INGESTION_RUN_ID
),
stage_bodies AS (
    SELECT *
    FROM APS_RAW.STAGE_CONTENT_BODIES
    WHERE INGESTION_RUN_ID = $STAGE_INGESTION_RUN_ID
),
stage_assets AS (
    SELECT *
    FROM APS_RAW.STAGE_CONTENT_ASSETS
    WHERE INGESTION_RUN_ID = $STAGE_INGESTION_RUN_ID
),
stage_entity_links AS (
    SELECT *
    FROM APS_RAW.STAGE_CONTENT_ENTITY_LINKS
    WHERE INGESTION_RUN_ID = $STAGE_INGESTION_RUN_ID
),
stage_dates AS (
    SELECT *
    FROM APS_RAW.STAGE_CONTENT_DATES
    WHERE INGESTION_RUN_ID = $STAGE_INGESTION_RUN_ID
),
duplicate_item_conflicts AS (
    SELECT
        CONTENT_ITEM_KEY,
        COUNT(DISTINCT STAGE_PAYLOAD_HASH) AS DISTINCT_PAYLOAD_HASH_COUNT
    FROM stage_items
    GROUP BY CONTENT_ITEM_KEY
    HAVING COUNT(DISTINCT STAGE_PAYLOAD_HASH) > 1
),
duplicate_version_conflicts AS (
    SELECT
        CONTENT_VERSION_KEY,
        COUNT(DISTINCT STAGE_PAYLOAD_HASH) AS DISTINCT_PAYLOAD_HASH_COUNT
    FROM stage_versions
    GROUP BY CONTENT_VERSION_KEY
    HAVING COUNT(DISTINCT STAGE_PAYLOAD_HASH) > 1
),
duplicate_body_conflicts AS (
    SELECT
        CONTENT_BODY_KEY,
        COUNT(DISTINCT STAGE_PAYLOAD_HASH) AS DISTINCT_PAYLOAD_HASH_COUNT
    FROM stage_bodies
    GROUP BY CONTENT_BODY_KEY
    HAVING COUNT(DISTINCT STAGE_PAYLOAD_HASH) > 1
),
multiple_current_candidates AS (
    SELECT
        CONTENT_ITEM_KEY,
        COUNT(DISTINCT CONTENT_VERSION_KEY) AS CURRENT_CANDIDATE_COUNT
    FROM stage_versions
    WHERE PROMOTE_TO_CURRENT
    GROUP BY CONTENT_ITEM_KEY
    HAVING COUNT(DISTINCT CONTENT_VERSION_KEY) > 1
),
primary_body_counts AS (
    SELECT
        CONTENT_VERSION_KEY,
        COUNT_IF(IS_PRIMARY_BODY) AS PRIMARY_BODY_COUNT
    FROM stage_bodies
    GROUP BY CONTENT_VERSION_KEY
),
orphan_asset_body_refs AS (
    SELECT sa.CONTENT_ASSET_KEY, sa.CONTENT_BODY_KEY
    FROM stage_assets sa
    LEFT JOIN stage_bodies sb
      ON sa.CONTENT_BODY_KEY = sb.CONTENT_BODY_KEY
    WHERE sa.CONTENT_BODY_KEY IS NOT NULL
      AND sb.CONTENT_BODY_KEY IS NULL
),
orphan_entity_body_refs AS (
    SELECT sel.CONTENT_ENTITY_LINK_KEY, sel.CONTENT_BODY_KEY
    FROM stage_entity_links sel
    LEFT JOIN stage_bodies sb
      ON sel.CONTENT_BODY_KEY = sb.CONTENT_BODY_KEY
    WHERE sel.CONTENT_BODY_KEY IS NOT NULL
      AND sb.CONTENT_BODY_KEY IS NULL
),
orphan_date_body_refs AS (
    SELECT sd.CONTENT_DATE_KEY, sd.CONTENT_BODY_KEY
    FROM stage_dates sd
    LEFT JOIN stage_bodies sb
      ON sd.CONTENT_BODY_KEY = sb.CONTENT_BODY_KEY
    WHERE sd.CONTENT_BODY_KEY IS NOT NULL
      AND sb.CONTENT_BODY_KEY IS NULL
)
SELECT
    'STAGE_CONTENT_ITEMS_KEY_CONFLICT' AS ISSUE_CODE,
    'STAGE_CONTENT_ITEMS' AS TABLE_NAME,
    CONTENT_ITEM_KEY AS BUSINESS_KEY,
    OBJECT_CONSTRUCT('distinct_payload_hash_count', DISTINCT_PAYLOAD_HASH_COUNT) AS ISSUE_CONTEXT
FROM duplicate_item_conflicts

UNION ALL

SELECT
    'STAGE_CONTENT_VERSIONS_KEY_CONFLICT' AS ISSUE_CODE,
    'STAGE_CONTENT_VERSIONS' AS TABLE_NAME,
    CONTENT_VERSION_KEY AS BUSINESS_KEY,
    OBJECT_CONSTRUCT('distinct_payload_hash_count', DISTINCT_PAYLOAD_HASH_COUNT) AS ISSUE_CONTEXT
FROM duplicate_version_conflicts

UNION ALL

SELECT
    'STAGE_CONTENT_BODIES_KEY_CONFLICT' AS ISSUE_CODE,
    'STAGE_CONTENT_BODIES' AS TABLE_NAME,
    CONTENT_BODY_KEY AS BUSINESS_KEY,
    OBJECT_CONSTRUCT('distinct_payload_hash_count', DISTINCT_PAYLOAD_HASH_COUNT) AS ISSUE_CONTEXT
FROM duplicate_body_conflicts

UNION ALL

SELECT
    'STAGE_MULTIPLE_CURRENT_VERSION_CANDIDATES' AS ISSUE_CODE,
    'STAGE_CONTENT_VERSIONS' AS TABLE_NAME,
    CONTENT_ITEM_KEY AS BUSINESS_KEY,
    OBJECT_CONSTRUCT('current_candidate_count', CURRENT_CANDIDATE_COUNT) AS ISSUE_CONTEXT
FROM multiple_current_candidates

UNION ALL

SELECT
    'STAGE_PRIMARY_BODY_CONFLICT' AS ISSUE_CODE,
    'STAGE_CONTENT_BODIES' AS TABLE_NAME,
    sv.CONTENT_VERSION_KEY AS BUSINESS_KEY,
    OBJECT_CONSTRUCT('primary_body_count', COALESCE(pbc.PRIMARY_BODY_COUNT, 0)) AS ISSUE_CONTEXT
FROM stage_versions sv
LEFT JOIN primary_body_counts pbc
  ON sv.CONTENT_VERSION_KEY = pbc.CONTENT_VERSION_KEY
WHERE COALESCE(pbc.PRIMARY_BODY_COUNT, 0) <> 1

UNION ALL

SELECT
    'STAGE_ORPHAN_ASSET_BODY_REFERENCE' AS ISSUE_CODE,
    'STAGE_CONTENT_ASSETS' AS TABLE_NAME,
    CONTENT_ASSET_KEY AS BUSINESS_KEY,
    OBJECT_CONSTRUCT('content_body_key', CONTENT_BODY_KEY) AS ISSUE_CONTEXT
FROM orphan_asset_body_refs

UNION ALL

SELECT
    'STAGE_ORPHAN_ENTITY_BODY_REFERENCE' AS ISSUE_CODE,
    'STAGE_CONTENT_ENTITY_LINKS' AS TABLE_NAME,
    CONTENT_ENTITY_LINK_KEY AS BUSINESS_KEY,
    OBJECT_CONSTRUCT('content_body_key', CONTENT_BODY_KEY) AS ISSUE_CONTEXT
FROM orphan_entity_body_refs

UNION ALL

SELECT
    'STAGE_ORPHAN_DATE_BODY_REFERENCE' AS ISSUE_CODE,
    'STAGE_CONTENT_DATES' AS TABLE_NAME,
    CONTENT_DATE_KEY AS BUSINESS_KEY,
    OBJECT_CONSTRUCT('content_body_key', CONTENT_BODY_KEY) AS ISSUE_CONTEXT
FROM orphan_date_body_refs
;

