-- Merge staged content items into APS_CORE.CONTENT_ITEMS.
--
-- Expected session input:
--   SET STAGE_INGESTION_RUN_ID = '<ingestion-run-id>';
-- Precondition:
--   adapters/markdown_notes/sql/001_pre_merge_validation.sql returns zero rows.

MERGE INTO APS_CORE.CONTENT_ITEMS AS target
USING (
    SELECT *
    FROM APS_RAW.STAGE_CONTENT_ITEMS
    WHERE INGESTION_RUN_ID = $STAGE_INGESTION_RUN_ID
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY CONTENT_ITEM_KEY
        ORDER BY STAGE_PAYLOAD_HASH, STAGED_AT DESC
    ) = 1
) AS source
ON target.CONTENT_ITEM_KEY = source.CONTENT_ITEM_KEY
WHEN MATCHED THEN UPDATE SET
    CONTENT_ID = source.CONTENT_ID,
    LOGICAL_SOURCE_KEY = source.LOGICAL_SOURCE_KEY,
    ITEM_IDENTITY_METHOD = source.ITEM_IDENTITY_METHOD,
    SOURCE_SYSTEM = source.SOURCE_SYSTEM,
    SOURCE_OBJECT_ID = source.SOURCE_OBJECT_ID,
    SOURCE_CONTAINER = source.SOURCE_CONTAINER,
    SOURCE_PATH = source.SOURCE_PATH,
    SOURCE_URI = source.SOURCE_URI,
    SOURCE_URI_NORMALIZED = source.SOURCE_URI_NORMALIZED,
    SOURCE_REFERENCE = source.SOURCE_REFERENCE,
    SOURCE_TYPE = source.SOURCE_TYPE,
    SOURCE_SUBTYPE = source.SOURCE_SUBTYPE,
    SOURCE_TITLE = source.SOURCE_TITLE,
    SOURCE_PROVENANCE = source.SOURCE_PROVENANCE,
    SOURCE_CREATED_AT = source.SOURCE_CREATED_AT,
    SOURCE_MODIFIED_AT = source.SOURCE_MODIFIED_AT,
    LAST_SEEN_AT = source.LAST_SEEN_AT,
    CANONICAL_CONTENT_HASH = source.CANONICAL_CONTENT_HASH,
    DUPLICATE_OF_CONTENT_ID = source.DUPLICATE_OF_CONTENT_ID,
    REVIEW_STATUS = COALESCE(source.REVIEW_STATUS, target.REVIEW_STATUS),
    STATUS_REASON = source.STATUS_REASON,
    IS_ACTIVE = COALESCE(source.IS_ACTIVE, target.IS_ACTIVE),
    METADATA = source.METADATA,
    UPDATED_AT = COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP())
WHEN NOT MATCHED THEN INSERT (
    CONTENT_ID,
    CONTENT_ITEM_KEY,
    LOGICAL_SOURCE_KEY,
    ITEM_IDENTITY_METHOD,
    SOURCE_SYSTEM,
    SOURCE_OBJECT_ID,
    SOURCE_CONTAINER,
    SOURCE_PATH,
    SOURCE_URI,
    SOURCE_URI_NORMALIZED,
    SOURCE_REFERENCE,
    SOURCE_TYPE,
    SOURCE_SUBTYPE,
    SOURCE_TITLE,
    SOURCE_PROVENANCE,
    SOURCE_CREATED_AT,
    SOURCE_MODIFIED_AT,
    FIRST_SEEN_AT,
    LAST_SEEN_AT,
    CANONICAL_CONTENT_HASH,
    DUPLICATE_OF_CONTENT_ID,
    REVIEW_STATUS,
    STATUS_REASON,
    IS_ACTIVE,
    METADATA,
    CREATED_AT,
    UPDATED_AT
) VALUES (
    source.CONTENT_ID,
    source.CONTENT_ITEM_KEY,
    source.LOGICAL_SOURCE_KEY,
    source.ITEM_IDENTITY_METHOD,
    source.SOURCE_SYSTEM,
    source.SOURCE_OBJECT_ID,
    source.SOURCE_CONTAINER,
    source.SOURCE_PATH,
    source.SOURCE_URI,
    source.SOURCE_URI_NORMALIZED,
    source.SOURCE_REFERENCE,
    source.SOURCE_TYPE,
    source.SOURCE_SUBTYPE,
    source.SOURCE_TITLE,
    source.SOURCE_PROVENANCE,
    source.SOURCE_CREATED_AT,
    source.SOURCE_MODIFIED_AT,
    COALESCE(source.FIRST_SEEN_AT, source.STAGED_AT, CURRENT_TIMESTAMP()),
    COALESCE(source.LAST_SEEN_AT, source.STAGED_AT, CURRENT_TIMESTAMP()),
    source.CANONICAL_CONTENT_HASH,
    source.DUPLICATE_OF_CONTENT_ID,
    COALESCE(source.REVIEW_STATUS, 'UNREVIEWED'),
    source.STATUS_REASON,
    COALESCE(source.IS_ACTIVE, TRUE),
    source.METADATA,
    COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP()),
    COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP())
);

