-- Merge staged content versions and promote current-version pointers atomically.
--
-- Expected session input:
--   SET STAGE_INGESTION_RUN_ID = '<ingestion-run-id>';
-- Precondition:
--   adapters/markdown_notes/sql/001_pre_merge_validation.sql returns zero rows.
--
-- This script intentionally keeps version merge, current-version demotion,
-- current-version promotion, and CONTENT_ITEM_CURRENT_VERSION pointer updates in
-- one transaction.

BEGIN;

MERGE INTO APS_CORE.CONTENT_VERSIONS AS target
USING (
    WITH stage_versions AS (
        SELECT *
        FROM APS_RAW.STAGE_CONTENT_VERSIONS
        WHERE INGESTION_RUN_ID = $STAGE_INGESTION_RUN_ID
        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY CONTENT_VERSION_KEY
            ORDER BY STAGE_PAYLOAD_HASH, STAGED_AT DESC
        ) = 1
    ),
    existing_version_stats AS (
        SELECT
            CONTENT_ID,
            MAX(VERSION_NUMBER) AS MAX_VERSION_NUMBER
        FROM APS_CORE.CONTENT_VERSIONS
        GROUP BY CONTENT_ID
    ),
    existing_same_fingerprint AS (
        SELECT
            cv.CONTENT_ID,
            cv.CONTENT_FINGERPRINT,
            cv.CONTENT_VERSION_ID AS DUPLICATE_OF_CONTENT_VERSION_ID,
            cv.CONTENT_VERSION_KEY AS DUPLICATE_OF_CONTENT_VERSION_KEY
        FROM APS_CORE.CONTENT_VERSIONS cv
        WHERE cv.CONTENT_FINGERPRINT IS NOT NULL
    )
    SELECT
        sv.CONTENT_VERSION_ID,
        sv.CONTENT_ID,
        sv.CONTENT_ITEM_KEY,
        sv.CONTENT_VERSION_KEY,
        COALESCE(evs.MAX_VERSION_NUMBER, 0) + 1 AS TARGET_VERSION_NUMBER,
        sv.VERSION_REASON,
        sv.INGESTION_RUN_ID,
        sv.RAW_RECORD_ID,
        sv.RAW_PAYLOAD_LOCATION,
        sv.NORMALIZED_PAYLOAD_LOCATION,
        sv.SOURCE_EXPORT_ID,
        sv.SOURCE_VERSION_ID,
        sv.SOURCE_EXPORTED_AT,
        sv.SOURCE_MODIFIED_AT,
        sv.ADAPTER_NAME,
        sv.ADAPTER_VERSION,
        sv.SOURCE_FILE_HASH,
        sv.BODY_HASH,
        sv.ASSET_FINGERPRINT,
        sv.CONTENT_FINGERPRINT,
        esf.DUPLICATE_OF_CONTENT_VERSION_ID,
        esf.DUPLICATE_OF_CONTENT_VERSION_KEY,
        CASE
            WHEN esf.DUPLICATE_OF_CONTENT_VERSION_ID IS NOT NULL
                 AND esf.DUPLICATE_OF_CONTENT_VERSION_KEY <> sv.CONTENT_VERSION_KEY
            THEN TRUE
            ELSE FALSE
        END AS IS_IDENTICAL_REEXPORT_DUPLICATE,
        sv.VERSION_STATUS,
        sv.PROMOTE_TO_CURRENT,
        sv.CURRENT_SELECTION_REASON,
        sv.PROPOSED_CURRENT_FROM_AT,
        sv.METADATA,
        sv.STAGED_AT
    FROM stage_versions sv
    LEFT JOIN existing_version_stats evs
      ON sv.CONTENT_ID = evs.CONTENT_ID
    LEFT JOIN existing_same_fingerprint esf
      ON sv.CONTENT_ID = esf.CONTENT_ID
     AND sv.CONTENT_FINGERPRINT = esf.CONTENT_FINGERPRINT
) AS source
ON target.CONTENT_VERSION_KEY = source.CONTENT_VERSION_KEY
WHEN MATCHED THEN UPDATE SET
    CONTENT_ID = source.CONTENT_ID,
    VERSION_REASON = source.VERSION_REASON,
    INGESTION_RUN_ID = source.INGESTION_RUN_ID,
    RAW_RECORD_ID = source.RAW_RECORD_ID,
    RAW_PAYLOAD_LOCATION = source.RAW_PAYLOAD_LOCATION,
    NORMALIZED_PAYLOAD_LOCATION = source.NORMALIZED_PAYLOAD_LOCATION,
    SOURCE_EXPORT_ID = source.SOURCE_EXPORT_ID,
    SOURCE_VERSION_ID = source.SOURCE_VERSION_ID,
    SOURCE_EXPORTED_AT = source.SOURCE_EXPORTED_AT,
    SOURCE_MODIFIED_AT = source.SOURCE_MODIFIED_AT,
    ADAPTER_NAME = source.ADAPTER_NAME,
    ADAPTER_VERSION = source.ADAPTER_VERSION,
    SOURCE_FILE_HASH = source.SOURCE_FILE_HASH,
    BODY_HASH = source.BODY_HASH,
    ASSET_FINGERPRINT = source.ASSET_FINGERPRINT,
    CONTENT_FINGERPRINT = source.CONTENT_FINGERPRINT,
    METADATA = source.METADATA,
    UPDATED_AT = COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP())
WHEN NOT MATCHED THEN INSERT (
    CONTENT_VERSION_ID,
    CONTENT_ID,
    CONTENT_VERSION_KEY,
    VERSION_NUMBER,
    VERSION_REASON,
    INGESTION_RUN_ID,
    RAW_RECORD_ID,
    RAW_PAYLOAD_LOCATION,
    NORMALIZED_PAYLOAD_LOCATION,
    SOURCE_EXPORT_ID,
    SOURCE_VERSION_ID,
    SOURCE_EXPORTED_AT,
    SOURCE_MODIFIED_AT,
    ADAPTER_NAME,
    ADAPTER_VERSION,
    SOURCE_FILE_HASH,
    BODY_HASH,
    ASSET_FINGERPRINT,
    CONTENT_FINGERPRINT,
    DUPLICATE_OF_CONTENT_VERSION_ID,
    DUPLICATE_REASON,
    VERSION_STATUS,
    IS_CURRENT,
    CURRENT_FROM_AT,
    CURRENT_TO_AT,
    METADATA,
    CREATED_AT,
    UPDATED_AT
) VALUES (
    source.CONTENT_VERSION_ID,
    source.CONTENT_ID,
    source.CONTENT_VERSION_KEY,
    source.TARGET_VERSION_NUMBER,
    CASE
        WHEN source.IS_IDENTICAL_REEXPORT_DUPLICATE THEN 'RE_EXPORT_IDENTICAL'
        ELSE source.VERSION_REASON
    END,
    source.INGESTION_RUN_ID,
    source.RAW_RECORD_ID,
    source.RAW_PAYLOAD_LOCATION,
    source.NORMALIZED_PAYLOAD_LOCATION,
    source.SOURCE_EXPORT_ID,
    source.SOURCE_VERSION_ID,
    source.SOURCE_EXPORTED_AT,
    source.SOURCE_MODIFIED_AT,
    source.ADAPTER_NAME,
    source.ADAPTER_VERSION,
    source.SOURCE_FILE_HASH,
    source.BODY_HASH,
    source.ASSET_FINGERPRINT,
    source.CONTENT_FINGERPRINT,
    source.DUPLICATE_OF_CONTENT_VERSION_ID,
    CASE
        WHEN source.IS_IDENTICAL_REEXPORT_DUPLICATE THEN 'IDENTICAL_CONTENT_FINGERPRINT'
        ELSE NULL
    END,
    CASE
        WHEN source.IS_IDENTICAL_REEXPORT_DUPLICATE THEN 'DUPLICATE'
        WHEN source.PROMOTE_TO_CURRENT THEN 'CURRENT'
        ELSE COALESCE(source.VERSION_STATUS, 'CANDIDATE')
    END,
    CASE
        WHEN source.IS_IDENTICAL_REEXPORT_DUPLICATE THEN FALSE
        ELSE COALESCE(source.PROMOTE_TO_CURRENT, FALSE)
    END,
    CASE
        WHEN source.IS_IDENTICAL_REEXPORT_DUPLICATE THEN NULL
        WHEN source.PROMOTE_TO_CURRENT THEN COALESCE(source.PROPOSED_CURRENT_FROM_AT, source.STAGED_AT, CURRENT_TIMESTAMP())
        ELSE NULL
    END,
    NULL,
    source.METADATA,
    COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP()),
    COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP())
);

UPDATE APS_CORE.CONTENT_VERSIONS AS previous_current
SET
    VERSION_STATUS = 'SUPERSEDED',
    IS_CURRENT = FALSE,
    CURRENT_TO_AT = COALESCE(promoted.PROPOSED_CURRENT_FROM_AT, promoted.STAGED_AT, CURRENT_TIMESTAMP()),
    SUPERSEDED_BY_CONTENT_VERSION_ID = promoted.CONTENT_VERSION_ID,
    UPDATED_AT = COALESCE(promoted.STAGED_AT, CURRENT_TIMESTAMP())
FROM (
    SELECT
        source.CONTENT_ID,
        source.CONTENT_VERSION_KEY,
        source.CONTENT_VERSION_ID,
        source.PROPOSED_CURRENT_FROM_AT,
        source.STAGED_AT
    FROM APS_RAW.STAGE_CONTENT_VERSIONS source
    JOIN APS_CORE.CONTENT_VERSIONS promoted_version
      ON promoted_version.CONTENT_VERSION_KEY = source.CONTENT_VERSION_KEY
    WHERE source.INGESTION_RUN_ID = $STAGE_INGESTION_RUN_ID
      AND source.PROMOTE_TO_CURRENT
      AND promoted_version.DUPLICATE_OF_CONTENT_VERSION_ID IS NULL
) AS promoted
WHERE previous_current.CONTENT_ID = promoted.CONTENT_ID
  AND previous_current.IS_CURRENT
  AND previous_current.CONTENT_VERSION_KEY <> promoted.CONTENT_VERSION_KEY;

UPDATE APS_CORE.CONTENT_VERSIONS AS promoted
SET
    VERSION_STATUS = 'CURRENT',
    IS_CURRENT = TRUE,
    CURRENT_FROM_AT = COALESCE(source.PROPOSED_CURRENT_FROM_AT, source.STAGED_AT, CURRENT_TIMESTAMP()),
    CURRENT_TO_AT = NULL,
    UPDATED_AT = COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP())
FROM APS_RAW.STAGE_CONTENT_VERSIONS AS source
WHERE source.INGESTION_RUN_ID = $STAGE_INGESTION_RUN_ID
  AND source.PROMOTE_TO_CURRENT
  AND promoted.CONTENT_VERSION_KEY = source.CONTENT_VERSION_KEY
  AND promoted.DUPLICATE_OF_CONTENT_VERSION_ID IS NULL;

MERGE INTO APS_CORE.CONTENT_ITEM_CURRENT_VERSION AS target
USING (
    SELECT
        promoted.CONTENT_ID,
        promoted.CONTENT_VERSION_ID AS CURRENT_CONTENT_VERSION_ID,
        promoted.CONTENT_VERSION_KEY AS CURRENT_CONTENT_VERSION_KEY,
        COALESCE(source.PROPOSED_CURRENT_FROM_AT, source.STAGED_AT, CURRENT_TIMESTAMP()) AS SELECTED_AT,
        COALESCE(source.CURRENT_SELECTION_REASON, source.VERSION_REASON, 'INITIAL_INGEST') AS SELECTION_REASON,
        COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP()) AS UPDATED_AT
    FROM APS_RAW.STAGE_CONTENT_VERSIONS source
    JOIN APS_CORE.CONTENT_VERSIONS promoted
      ON promoted.CONTENT_VERSION_KEY = source.CONTENT_VERSION_KEY
    WHERE source.INGESTION_RUN_ID = $STAGE_INGESTION_RUN_ID
      AND source.PROMOTE_TO_CURRENT
      AND promoted.DUPLICATE_OF_CONTENT_VERSION_ID IS NULL
) AS source
ON target.CONTENT_ID = source.CONTENT_ID
WHEN MATCHED THEN UPDATE SET
    CURRENT_CONTENT_VERSION_ID = source.CURRENT_CONTENT_VERSION_ID,
    CURRENT_CONTENT_VERSION_KEY = source.CURRENT_CONTENT_VERSION_KEY,
    SELECTED_AT = source.SELECTED_AT,
    SELECTION_REASON = source.SELECTION_REASON,
    UPDATED_AT = source.UPDATED_AT
WHEN NOT MATCHED THEN INSERT (
    CONTENT_ID,
    CURRENT_CONTENT_VERSION_ID,
    CURRENT_CONTENT_VERSION_KEY,
    SELECTED_AT,
    SELECTION_REASON,
    UPDATED_AT
) VALUES (
    source.CONTENT_ID,
    source.CURRENT_CONTENT_VERSION_ID,
    source.CURRENT_CONTENT_VERSION_KEY,
    source.SELECTED_AT,
    source.SELECTION_REASON,
    source.UPDATED_AT
);

COMMIT;

