-- Merge staged child rows into APS_CORE child tables using business keys.
--
-- Expected session input:
--   SET STAGE_INGESTION_RUN_ID = '<ingestion-run-id>';
-- Precondition:
--   adapters/markdown_notes/sql/001_pre_merge_validation.sql returns zero rows.

MERGE INTO APS_CORE.CONTENT_BODIES AS target
USING (
    SELECT
        sb.CONTENT_BODY_ID,
        ci.CONTENT_ID,
        cv.CONTENT_VERSION_ID,
        sb.CONTENT_BODY_KEY,
        parent.CONTENT_BODY_ID AS PARENT_CONTENT_BODY_ID,
        sb.BODY_ROLE,
        sb.BODY_FORMAT,
        sb.BODY_TEXT,
        sb.BODY_LOCATION,
        sb.SECTION_PATH,
        sb.SECTION_TITLE,
        sb.SECTION_LEVEL,
        sb.SECTION_ORDER,
        sb.ANCHOR_START,
        sb.ANCHOR_END,
        sb.IS_PRIMARY_BODY,
        sb.BODY_HASH,
        sb.NORMALIZED_BODY_HASH,
        sb.LANGUAGE_CODE,
        sb.TOKEN_COUNT,
        sb.EXTRACTION_METHOD,
        sb.EXTRACTION_CONFIDENCE,
        sb.METADATA,
        sb.STAGED_AT
    FROM APS_RAW.STAGE_CONTENT_BODIES sb
    JOIN APS_CORE.CONTENT_ITEMS ci
      ON ci.CONTENT_ITEM_KEY = sb.CONTENT_ITEM_KEY
    JOIN APS_CORE.CONTENT_VERSIONS cv
      ON cv.CONTENT_VERSION_KEY = sb.CONTENT_VERSION_KEY
    LEFT JOIN APS_CORE.CONTENT_BODIES parent
      ON parent.CONTENT_BODY_KEY = sb.PARENT_CONTENT_BODY_KEY
    WHERE sb.INGESTION_RUN_ID = $STAGE_INGESTION_RUN_ID
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY sb.CONTENT_BODY_KEY
        ORDER BY sb.STAGE_PAYLOAD_HASH, sb.STAGED_AT DESC
    ) = 1
) AS source
ON target.CONTENT_BODY_KEY = source.CONTENT_BODY_KEY
WHEN MATCHED THEN UPDATE SET
    CONTENT_BODY_ID = source.CONTENT_BODY_ID,
    CONTENT_ID = source.CONTENT_ID,
    CONTENT_VERSION_ID = source.CONTENT_VERSION_ID,
    PARENT_CONTENT_BODY_ID = source.PARENT_CONTENT_BODY_ID,
    BODY_ROLE = source.BODY_ROLE,
    BODY_FORMAT = source.BODY_FORMAT,
    BODY_TEXT = source.BODY_TEXT,
    BODY_LOCATION = source.BODY_LOCATION,
    SECTION_PATH = source.SECTION_PATH,
    SECTION_TITLE = source.SECTION_TITLE,
    SECTION_LEVEL = source.SECTION_LEVEL,
    SECTION_ORDER = source.SECTION_ORDER,
    ANCHOR_START = source.ANCHOR_START,
    ANCHOR_END = source.ANCHOR_END,
    IS_PRIMARY_BODY = source.IS_PRIMARY_BODY,
    BODY_HASH = source.BODY_HASH,
    NORMALIZED_BODY_HASH = source.NORMALIZED_BODY_HASH,
    LANGUAGE_CODE = source.LANGUAGE_CODE,
    TOKEN_COUNT = source.TOKEN_COUNT,
    EXTRACTION_METHOD = source.EXTRACTION_METHOD,
    EXTRACTION_CONFIDENCE = source.EXTRACTION_CONFIDENCE,
    METADATA = source.METADATA,
    UPDATED_AT = COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP())
WHEN NOT MATCHED THEN INSERT (
    CONTENT_BODY_ID,
    CONTENT_ID,
    CONTENT_VERSION_ID,
    CONTENT_BODY_KEY,
    PARENT_CONTENT_BODY_ID,
    BODY_ROLE,
    BODY_FORMAT,
    BODY_TEXT,
    BODY_LOCATION,
    SECTION_PATH,
    SECTION_TITLE,
    SECTION_LEVEL,
    SECTION_ORDER,
    ANCHOR_START,
    ANCHOR_END,
    IS_PRIMARY_BODY,
    BODY_HASH,
    NORMALIZED_BODY_HASH,
    LANGUAGE_CODE,
    TOKEN_COUNT,
    EXTRACTION_METHOD,
    EXTRACTION_CONFIDENCE,
    METADATA,
    CREATED_AT,
    UPDATED_AT
) VALUES (
    source.CONTENT_BODY_ID,
    source.CONTENT_ID,
    source.CONTENT_VERSION_ID,
    source.CONTENT_BODY_KEY,
    source.PARENT_CONTENT_BODY_ID,
    source.BODY_ROLE,
    source.BODY_FORMAT,
    source.BODY_TEXT,
    source.BODY_LOCATION,
    source.SECTION_PATH,
    source.SECTION_TITLE,
    source.SECTION_LEVEL,
    source.SECTION_ORDER,
    source.ANCHOR_START,
    source.ANCHOR_END,
    source.IS_PRIMARY_BODY,
    source.BODY_HASH,
    source.NORMALIZED_BODY_HASH,
    source.LANGUAGE_CODE,
    source.TOKEN_COUNT,
    source.EXTRACTION_METHOD,
    source.EXTRACTION_CONFIDENCE,
    source.METADATA,
    COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP()),
    COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP())
);

MERGE INTO APS_CORE.CONTENT_ASSETS AS target
USING (
    SELECT
        sa.CONTENT_ASSET_ID,
        ci.CONTENT_ID,
        cv.CONTENT_VERSION_ID,
        cb.CONTENT_BODY_ID,
        sa.CONTENT_ASSET_KEY,
        sa.ASSET_ROLE,
        sa.ASSET_TYPE,
        sa.SOURCE_ASSET_URI,
        sa.STORAGE_URI,
        sa.FILE_NAME,
        sa.MIME_TYPE,
        sa.ASSET_HASH,
        sa.ASSET_ORDER,
        sa.BODY_ANCHOR,
        sa.ALT_TEXT,
        sa.CAPTION_TEXT,
        sa.OCR_TEXT,
        sa.CHART_DATA,
        sa.EXTRACTION_METHOD,
        sa.EXTRACTION_STATUS,
        sa.EXTRACTION_CONFIDENCE,
        sa.METADATA,
        sa.STAGED_AT
    FROM APS_RAW.STAGE_CONTENT_ASSETS sa
    JOIN APS_CORE.CONTENT_ITEMS ci
      ON ci.CONTENT_ITEM_KEY = sa.CONTENT_ITEM_KEY
    JOIN APS_CORE.CONTENT_VERSIONS cv
      ON cv.CONTENT_VERSION_KEY = sa.CONTENT_VERSION_KEY
    LEFT JOIN APS_CORE.CONTENT_BODIES cb
      ON cb.CONTENT_BODY_KEY = sa.CONTENT_BODY_KEY
    WHERE sa.INGESTION_RUN_ID = $STAGE_INGESTION_RUN_ID
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY sa.CONTENT_ASSET_KEY
        ORDER BY sa.STAGE_PAYLOAD_HASH, sa.STAGED_AT DESC
    ) = 1
) AS source
ON target.CONTENT_ASSET_KEY = source.CONTENT_ASSET_KEY
WHEN MATCHED THEN UPDATE SET
    CONTENT_ASSET_ID = source.CONTENT_ASSET_ID,
    CONTENT_ID = source.CONTENT_ID,
    CONTENT_VERSION_ID = source.CONTENT_VERSION_ID,
    CONTENT_BODY_ID = source.CONTENT_BODY_ID,
    ASSET_ROLE = source.ASSET_ROLE,
    ASSET_TYPE = source.ASSET_TYPE,
    SOURCE_ASSET_URI = source.SOURCE_ASSET_URI,
    STORAGE_URI = source.STORAGE_URI,
    FILE_NAME = source.FILE_NAME,
    MIME_TYPE = source.MIME_TYPE,
    ASSET_HASH = source.ASSET_HASH,
    ASSET_ORDER = source.ASSET_ORDER,
    BODY_ANCHOR = source.BODY_ANCHOR,
    ALT_TEXT = source.ALT_TEXT,
    CAPTION_TEXT = source.CAPTION_TEXT,
    OCR_TEXT = source.OCR_TEXT,
    CHART_DATA = source.CHART_DATA,
    EXTRACTION_METHOD = source.EXTRACTION_METHOD,
    EXTRACTION_STATUS = source.EXTRACTION_STATUS,
    EXTRACTION_CONFIDENCE = source.EXTRACTION_CONFIDENCE,
    METADATA = source.METADATA,
    UPDATED_AT = COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP())
WHEN NOT MATCHED THEN INSERT (
    CONTENT_ASSET_ID,
    CONTENT_ID,
    CONTENT_VERSION_ID,
    CONTENT_BODY_ID,
    CONTENT_ASSET_KEY,
    ASSET_ROLE,
    ASSET_TYPE,
    SOURCE_ASSET_URI,
    STORAGE_URI,
    FILE_NAME,
    MIME_TYPE,
    ASSET_HASH,
    ASSET_ORDER,
    BODY_ANCHOR,
    ALT_TEXT,
    CAPTION_TEXT,
    OCR_TEXT,
    CHART_DATA,
    EXTRACTION_METHOD,
    EXTRACTION_STATUS,
    EXTRACTION_CONFIDENCE,
    METADATA,
    CREATED_AT,
    UPDATED_AT
) VALUES (
    source.CONTENT_ASSET_ID,
    source.CONTENT_ID,
    source.CONTENT_VERSION_ID,
    source.CONTENT_BODY_ID,
    source.CONTENT_ASSET_KEY,
    source.ASSET_ROLE,
    source.ASSET_TYPE,
    source.SOURCE_ASSET_URI,
    source.STORAGE_URI,
    source.FILE_NAME,
    source.MIME_TYPE,
    source.ASSET_HASH,
    source.ASSET_ORDER,
    source.BODY_ANCHOR,
    source.ALT_TEXT,
    source.CAPTION_TEXT,
    source.OCR_TEXT,
    source.CHART_DATA,
    source.EXTRACTION_METHOD,
    source.EXTRACTION_STATUS,
    source.EXTRACTION_CONFIDENCE,
    source.METADATA,
    COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP()),
    COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP())
);

MERGE INTO APS_CORE.CONTENT_SCOPES AS target
USING (
    SELECT
        ss.CONTENT_SCOPE_ID,
        ci.CONTENT_ID,
        cv.CONTENT_VERSION_ID,
        ss.CONTENT_SCOPE_KEY,
        ss.SCOPE_TYPE,
        ss.SCOPE_LABEL,
        ss.SCOPE_ENTITY_TYPE,
        ss.SCOPE_ENTITY_ID,
        ss.SCOPE_ENTITY_NAME,
        ss.IS_PRIMARY_SCOPE,
        ss.CONFIDENCE,
        ss.EVIDENCE_TEXT,
        ss.EVIDENCE,
        ss.CLASSIFICATION_METHOD,
        ss.REVIEW_STATUS,
        ss.METADATA,
        ss.STAGED_AT
    FROM APS_RAW.STAGE_CONTENT_SCOPES ss
    JOIN APS_CORE.CONTENT_ITEMS ci
      ON ci.CONTENT_ITEM_KEY = ss.CONTENT_ITEM_KEY
    JOIN APS_CORE.CONTENT_VERSIONS cv
      ON cv.CONTENT_VERSION_KEY = ss.CONTENT_VERSION_KEY
    WHERE ss.INGESTION_RUN_ID = $STAGE_INGESTION_RUN_ID
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ss.CONTENT_SCOPE_KEY
        ORDER BY ss.STAGE_PAYLOAD_HASH, ss.STAGED_AT DESC
    ) = 1
) AS source
ON target.CONTENT_SCOPE_KEY = source.CONTENT_SCOPE_KEY
WHEN MATCHED THEN UPDATE SET
    CONTENT_SCOPE_ID = source.CONTENT_SCOPE_ID,
    CONTENT_ID = source.CONTENT_ID,
    CONTENT_VERSION_ID = source.CONTENT_VERSION_ID,
    SCOPE_TYPE = source.SCOPE_TYPE,
    SCOPE_LABEL = source.SCOPE_LABEL,
    SCOPE_ENTITY_TYPE = source.SCOPE_ENTITY_TYPE,
    SCOPE_ENTITY_ID = source.SCOPE_ENTITY_ID,
    SCOPE_ENTITY_NAME = source.SCOPE_ENTITY_NAME,
    IS_PRIMARY_SCOPE = source.IS_PRIMARY_SCOPE,
    CONFIDENCE = source.CONFIDENCE,
    EVIDENCE_TEXT = source.EVIDENCE_TEXT,
    EVIDENCE = source.EVIDENCE,
    CLASSIFICATION_METHOD = source.CLASSIFICATION_METHOD,
    REVIEW_STATUS = source.REVIEW_STATUS,
    METADATA = source.METADATA,
    UPDATED_AT = COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP())
WHEN NOT MATCHED THEN INSERT (
    CONTENT_SCOPE_ID,
    CONTENT_ID,
    CONTENT_VERSION_ID,
    CONTENT_SCOPE_KEY,
    SCOPE_TYPE,
    SCOPE_LABEL,
    SCOPE_ENTITY_TYPE,
    SCOPE_ENTITY_ID,
    SCOPE_ENTITY_NAME,
    IS_PRIMARY_SCOPE,
    CONFIDENCE,
    EVIDENCE_TEXT,
    EVIDENCE,
    CLASSIFICATION_METHOD,
    REVIEW_STATUS,
    METADATA,
    CREATED_AT,
    UPDATED_AT
) VALUES (
    source.CONTENT_SCOPE_ID,
    source.CONTENT_ID,
    source.CONTENT_VERSION_ID,
    source.CONTENT_SCOPE_KEY,
    source.SCOPE_TYPE,
    source.SCOPE_LABEL,
    source.SCOPE_ENTITY_TYPE,
    source.SCOPE_ENTITY_ID,
    source.SCOPE_ENTITY_NAME,
    source.IS_PRIMARY_SCOPE,
    source.CONFIDENCE,
    source.EVIDENCE_TEXT,
    source.EVIDENCE,
    source.CLASSIFICATION_METHOD,
    source.REVIEW_STATUS,
    source.METADATA,
    COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP()),
    COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP())
);

MERGE INTO APS_CORE.CONTENT_ENTITY_LINKS AS target
USING (
    SELECT
        sel.CONTENT_ENTITY_LINK_ID,
        ci.CONTENT_ID,
        cv.CONTENT_VERSION_ID,
        cb.CONTENT_BODY_ID,
        ca.CONTENT_ASSET_ID,
        sel.CONTENT_ENTITY_LINK_KEY,
        sel.ENTITY_TYPE,
        sel.ENTITY_ID,
        sel.ENTITY_NAME,
        sel.MENTION_TEXT,
        sel.MENTION_START,
        sel.MENTION_END,
        sel.MENTION_CONTEXT,
        sel.LINK_ROLE,
        sel.ANCHOR_SCOPE,
        sel.RESOLUTION_METHOD,
        sel.CONFIDENCE,
        sel.EVIDENCE_TEXT,
        sel.EVIDENCE,
        sel.REVIEW_STATUS,
        sel.IS_PRIMARY_SUBJECT,
        sel.METADATA,
        sel.STAGED_AT
    FROM APS_RAW.STAGE_CONTENT_ENTITY_LINKS sel
    JOIN APS_CORE.CONTENT_ITEMS ci
      ON ci.CONTENT_ITEM_KEY = sel.CONTENT_ITEM_KEY
    JOIN APS_CORE.CONTENT_VERSIONS cv
      ON cv.CONTENT_VERSION_KEY = sel.CONTENT_VERSION_KEY
    LEFT JOIN APS_CORE.CONTENT_BODIES cb
      ON cb.CONTENT_BODY_KEY = sel.CONTENT_BODY_KEY
    LEFT JOIN APS_CORE.CONTENT_ASSETS ca
      ON ca.CONTENT_ASSET_KEY = sel.CONTENT_ASSET_KEY
    WHERE sel.INGESTION_RUN_ID = $STAGE_INGESTION_RUN_ID
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY sel.CONTENT_ENTITY_LINK_KEY
        ORDER BY sel.STAGE_PAYLOAD_HASH, sel.STAGED_AT DESC
    ) = 1
) AS source
ON target.CONTENT_ENTITY_LINK_KEY = source.CONTENT_ENTITY_LINK_KEY
WHEN MATCHED THEN UPDATE SET
    CONTENT_ENTITY_LINK_ID = source.CONTENT_ENTITY_LINK_ID,
    CONTENT_ID = source.CONTENT_ID,
    CONTENT_VERSION_ID = source.CONTENT_VERSION_ID,
    CONTENT_BODY_ID = source.CONTENT_BODY_ID,
    CONTENT_ASSET_ID = source.CONTENT_ASSET_ID,
    ENTITY_TYPE = source.ENTITY_TYPE,
    ENTITY_ID = source.ENTITY_ID,
    ENTITY_NAME = source.ENTITY_NAME,
    MENTION_TEXT = source.MENTION_TEXT,
    MENTION_START = source.MENTION_START,
    MENTION_END = source.MENTION_END,
    MENTION_CONTEXT = source.MENTION_CONTEXT,
    LINK_ROLE = source.LINK_ROLE,
    ANCHOR_SCOPE = source.ANCHOR_SCOPE,
    RESOLUTION_METHOD = source.RESOLUTION_METHOD,
    CONFIDENCE = source.CONFIDENCE,
    EVIDENCE_TEXT = source.EVIDENCE_TEXT,
    EVIDENCE = source.EVIDENCE,
    REVIEW_STATUS = source.REVIEW_STATUS,
    IS_PRIMARY_SUBJECT = source.IS_PRIMARY_SUBJECT,
    METADATA = source.METADATA,
    UPDATED_AT = COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP())
WHEN NOT MATCHED THEN INSERT (
    CONTENT_ENTITY_LINK_ID,
    CONTENT_ID,
    CONTENT_VERSION_ID,
    CONTENT_BODY_ID,
    CONTENT_ASSET_ID,
    CONTENT_ENTITY_LINK_KEY,
    ENTITY_TYPE,
    ENTITY_ID,
    ENTITY_NAME,
    MENTION_TEXT,
    MENTION_START,
    MENTION_END,
    MENTION_CONTEXT,
    LINK_ROLE,
    ANCHOR_SCOPE,
    RESOLUTION_METHOD,
    CONFIDENCE,
    EVIDENCE_TEXT,
    EVIDENCE,
    REVIEW_STATUS,
    IS_PRIMARY_SUBJECT,
    METADATA,
    CREATED_AT,
    UPDATED_AT
) VALUES (
    source.CONTENT_ENTITY_LINK_ID,
    source.CONTENT_ID,
    source.CONTENT_VERSION_ID,
    source.CONTENT_BODY_ID,
    source.CONTENT_ASSET_ID,
    source.CONTENT_ENTITY_LINK_KEY,
    source.ENTITY_TYPE,
    source.ENTITY_ID,
    source.ENTITY_NAME,
    source.MENTION_TEXT,
    source.MENTION_START,
    source.MENTION_END,
    source.MENTION_CONTEXT,
    source.LINK_ROLE,
    source.ANCHOR_SCOPE,
    source.RESOLUTION_METHOD,
    source.CONFIDENCE,
    source.EVIDENCE_TEXT,
    source.EVIDENCE,
    source.REVIEW_STATUS,
    source.IS_PRIMARY_SUBJECT,
    source.METADATA,
    COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP()),
    COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP())
);

MERGE INTO APS_CORE.CONTENT_DATES AS target
USING (
    SELECT
        sd.CONTENT_DATE_ID,
        ci.CONTENT_ID,
        cv.CONTENT_VERSION_ID,
        cb.CONTENT_BODY_ID,
        sd.CONTENT_DATE_KEY,
        sd.DATE_TYPE,
        sd.DATE_ROLE,
        sd.DATE_VALUE,
        sd.TIMESTAMP_VALUE,
        sd.PERIOD_START_DATE,
        sd.PERIOD_END_DATE,
        sd.DATE_GRANULARITY,
        sd.DATE_TEXT,
        sd.DATE_SOURCE,
        sd.IS_PRIMARY_CANDIDATE,
        sd.DATE_PRIORITY_OVERRIDE,
        sd.CONFIDENCE,
        sd.EVIDENCE_TEXT,
        sd.EVIDENCE,
        sd.INFERENCE_METHOD,
        sd.REVIEW_STATUS,
        sd.METADATA,
        sd.STAGED_AT
    FROM APS_RAW.STAGE_CONTENT_DATES sd
    JOIN APS_CORE.CONTENT_ITEMS ci
      ON ci.CONTENT_ITEM_KEY = sd.CONTENT_ITEM_KEY
    JOIN APS_CORE.CONTENT_VERSIONS cv
      ON cv.CONTENT_VERSION_KEY = sd.CONTENT_VERSION_KEY
    LEFT JOIN APS_CORE.CONTENT_BODIES cb
      ON cb.CONTENT_BODY_KEY = sd.CONTENT_BODY_KEY
    WHERE sd.INGESTION_RUN_ID = $STAGE_INGESTION_RUN_ID
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY sd.CONTENT_DATE_KEY
        ORDER BY sd.STAGE_PAYLOAD_HASH, sd.STAGED_AT DESC
    ) = 1
) AS source
ON target.CONTENT_DATE_KEY = source.CONTENT_DATE_KEY
WHEN MATCHED THEN UPDATE SET
    CONTENT_DATE_ID = source.CONTENT_DATE_ID,
    CONTENT_ID = source.CONTENT_ID,
    CONTENT_VERSION_ID = source.CONTENT_VERSION_ID,
    CONTENT_BODY_ID = source.CONTENT_BODY_ID,
    DATE_TYPE = source.DATE_TYPE,
    DATE_ROLE = source.DATE_ROLE,
    DATE_VALUE = source.DATE_VALUE,
    TIMESTAMP_VALUE = source.TIMESTAMP_VALUE,
    PERIOD_START_DATE = source.PERIOD_START_DATE,
    PERIOD_END_DATE = source.PERIOD_END_DATE,
    DATE_GRANULARITY = source.DATE_GRANULARITY,
    DATE_TEXT = source.DATE_TEXT,
    DATE_SOURCE = source.DATE_SOURCE,
    IS_PRIMARY_CANDIDATE = source.IS_PRIMARY_CANDIDATE,
    DATE_PRIORITY_OVERRIDE = source.DATE_PRIORITY_OVERRIDE,
    CONFIDENCE = source.CONFIDENCE,
    EVIDENCE_TEXT = source.EVIDENCE_TEXT,
    EVIDENCE = source.EVIDENCE,
    INFERENCE_METHOD = source.INFERENCE_METHOD,
    REVIEW_STATUS = source.REVIEW_STATUS,
    METADATA = source.METADATA,
    UPDATED_AT = COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP())
WHEN NOT MATCHED THEN INSERT (
    CONTENT_DATE_ID,
    CONTENT_ID,
    CONTENT_VERSION_ID,
    CONTENT_BODY_ID,
    CONTENT_DATE_KEY,
    DATE_TYPE,
    DATE_ROLE,
    DATE_VALUE,
    TIMESTAMP_VALUE,
    PERIOD_START_DATE,
    PERIOD_END_DATE,
    DATE_GRANULARITY,
    DATE_TEXT,
    DATE_SOURCE,
    IS_PRIMARY_CANDIDATE,
    DATE_PRIORITY_OVERRIDE,
    CONFIDENCE,
    EVIDENCE_TEXT,
    EVIDENCE,
    INFERENCE_METHOD,
    REVIEW_STATUS,
    METADATA,
    CREATED_AT,
    UPDATED_AT
) VALUES (
    source.CONTENT_DATE_ID,
    source.CONTENT_ID,
    source.CONTENT_VERSION_ID,
    source.CONTENT_BODY_ID,
    source.CONTENT_DATE_KEY,
    source.DATE_TYPE,
    source.DATE_ROLE,
    source.DATE_VALUE,
    source.TIMESTAMP_VALUE,
    source.PERIOD_START_DATE,
    source.PERIOD_END_DATE,
    source.DATE_GRANULARITY,
    source.DATE_TEXT,
    source.DATE_SOURCE,
    source.IS_PRIMARY_CANDIDATE,
    source.DATE_PRIORITY_OVERRIDE,
    source.CONFIDENCE,
    source.EVIDENCE_TEXT,
    source.EVIDENCE,
    source.INFERENCE_METHOD,
    source.REVIEW_STATUS,
    source.METADATA,
    COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP()),
    COALESCE(source.STAGED_AT, CURRENT_TIMESTAMP())
);

