-- APS generic content canonical model v2.
--
-- APS_RAW owns ingestion files, raw payloads, and lineage. APS_CORE owns normalized
-- source truth. These tables preserve logical content objects without forcing broad
-- notes into investment-shaped records too early.
--
-- Snowflake standard-table primary, foreign, and unique constraints are metadata,
-- not full integrity enforcement. The business keys and health views in this repo
-- are part of the ingestion contract, not optional documentation.

CREATE SCHEMA IF NOT EXISTS APS_CORE;

CREATE TABLE IF NOT EXISTS APS_CORE.CONTENT_ITEMS (
    CONTENT_ID VARCHAR NOT NULL,
    CONTENT_ITEM_KEY VARCHAR NOT NULL,
    LOGICAL_SOURCE_KEY VARCHAR NOT NULL,
    ITEM_IDENTITY_METHOD VARCHAR NOT NULL,
    SOURCE_SYSTEM VARCHAR NOT NULL,
    SOURCE_OBJECT_ID VARCHAR,
    SOURCE_CONTAINER VARCHAR,
    SOURCE_PATH VARCHAR,
    SOURCE_URI VARCHAR,
    SOURCE_URI_NORMALIZED VARCHAR,
    SOURCE_REFERENCE VARCHAR,
    SOURCE_TYPE VARCHAR NOT NULL,
    SOURCE_SUBTYPE VARCHAR,
    SOURCE_TITLE VARCHAR,
    SOURCE_PROVENANCE VARIANT,
    SOURCE_CREATED_AT TIMESTAMP_NTZ,
    SOURCE_MODIFIED_AT TIMESTAMP_NTZ,
    FIRST_SEEN_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    LAST_SEEN_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CANONICAL_CONTENT_HASH VARCHAR,
    DUPLICATE_OF_CONTENT_ID VARCHAR,
    REVIEW_STATUS VARCHAR NOT NULL DEFAULT 'UNREVIEWED',
    STATUS_REASON VARCHAR,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    METADATA VARIANT,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CONTENT_ITEMS PRIMARY KEY (CONTENT_ID),
    CONSTRAINT UK_CONTENT_ITEMS_ITEM_KEY UNIQUE (CONTENT_ITEM_KEY)
);

COMMENT ON TABLE APS_CORE.CONTENT_ITEMS IS
    'One logical source object such as a PM note, strategy note, portfolio update, markdown export, webcast, or future source.';
COMMENT ON COLUMN APS_CORE.CONTENT_ITEMS.CONTENT_ITEM_KEY IS
    'Adapter-produced merge key for the logical content item. Prefer source object id. Fall back to normalized source URI/path. Do not use raw URL alone when a stable object id exists.';
COMMENT ON COLUMN APS_CORE.CONTENT_ITEMS.LOGICAL_SOURCE_KEY IS
    'Human-readable stable source identity used for traceability. Usually same input material as CONTENT_ITEM_KEY before hashing or namespacing.';
COMMENT ON COLUMN APS_CORE.CONTENT_ITEMS.ITEM_IDENTITY_METHOD IS
    'How the adapter chose CONTENT_ITEM_KEY, for example SOURCE_OBJECT_ID, NORMALIZED_URI, CONTAINER_PATH, CONTENT_HASH_RECONCILED.';
COMMENT ON COLUMN APS_CORE.CONTENT_ITEMS.CANONICAL_CONTENT_HASH IS
    'Normalized content fingerprint used for duplicate detection across source systems, moved files, and re-exports. This is not the primary item identity when source object ids exist.';
COMMENT ON COLUMN APS_CORE.CONTENT_ITEMS.DUPLICATE_OF_CONTENT_ID IS
    'Canonical item this item duplicates when duplicate detection finds separate item keys for the same logical content.';
COMMENT ON COLUMN APS_CORE.CONTENT_ITEMS.REVIEW_STATUS IS
    'Human or workflow review state, for example UNREVIEWED, APPROVED, NEEDS_REVIEW, REJECTED, DUPLICATE, SUPERSEDED.';

CREATE TABLE IF NOT EXISTS APS_CORE.CONTENT_VERSIONS (
    CONTENT_VERSION_ID VARCHAR NOT NULL,
    CONTENT_ID VARCHAR NOT NULL,
    CONTENT_VERSION_KEY VARCHAR NOT NULL,
    VERSION_NUMBER NUMBER(38, 0) NOT NULL,
    VERSION_REASON VARCHAR NOT NULL DEFAULT 'INITIAL_INGEST',
    INGESTION_RUN_ID VARCHAR,
    RAW_RECORD_ID VARCHAR,
    RAW_PAYLOAD_LOCATION VARCHAR,
    NORMALIZED_PAYLOAD_LOCATION VARCHAR,
    SOURCE_EXPORT_ID VARCHAR,
    SOURCE_VERSION_ID VARCHAR,
    SOURCE_EXPORTED_AT TIMESTAMP_NTZ,
    SOURCE_MODIFIED_AT TIMESTAMP_NTZ,
    ADAPTER_NAME VARCHAR,
    ADAPTER_VERSION VARCHAR,
    SOURCE_FILE_HASH VARCHAR,
    BODY_HASH VARCHAR,
    ASSET_FINGERPRINT VARCHAR,
    CONTENT_FINGERPRINT VARCHAR,
    PREVIOUS_CONTENT_VERSION_ID VARCHAR,
    SUPERSEDED_BY_CONTENT_VERSION_ID VARCHAR,
    DUPLICATE_OF_CONTENT_VERSION_ID VARCHAR,
    DUPLICATE_REASON VARCHAR,
    VERSION_STATUS VARCHAR NOT NULL DEFAULT 'CANDIDATE',
    IS_CURRENT BOOLEAN NOT NULL DEFAULT FALSE,
    CURRENT_FROM_AT TIMESTAMP_NTZ,
    CURRENT_TO_AT TIMESTAMP_NTZ,
    METADATA VARIANT,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CONTENT_VERSIONS PRIMARY KEY (CONTENT_VERSION_ID),
    CONSTRAINT UK_CONTENT_VERSIONS_VERSION_KEY UNIQUE (CONTENT_VERSION_KEY),
    CONSTRAINT FK_CONTENT_VERSIONS_ITEM FOREIGN KEY (CONTENT_ID)
        REFERENCES APS_CORE.CONTENT_ITEMS (CONTENT_ID)
);

COMMENT ON TABLE APS_CORE.CONTENT_VERSIONS IS
    'Exports, re-exports, revisions, ingestion runs, fingerprints, duplicate detection, and version lineage for content items.';
COMMENT ON COLUMN APS_CORE.CONTENT_VERSIONS.CONTENT_VERSION_KEY IS
    'Adapter-produced merge key for one normalized version. Recommended shape: CONTENT_ITEM_KEY + content fingerprint, or CONTENT_ITEM_KEY + source version id when the source has immutable versions.';
COMMENT ON COLUMN APS_CORE.CONTENT_VERSIONS.VERSION_REASON IS
    'Why this version exists, for example INITIAL_INGEST, SOURCE_REVISION, RE_EXPORT_IDENTICAL, MOVED_FILE, ADAPTER_REPROCESS, DUPLICATE_DETECTED.';
COMMENT ON COLUMN APS_CORE.CONTENT_VERSIONS.CONTENT_FINGERPRINT IS
    'Composite fingerprint across normalized body and assets. Prefer this over URL-only dedupe.';
COMMENT ON COLUMN APS_CORE.CONTENT_VERSIONS.VERSION_STATUS IS
    'Version lifecycle state, for example CANDIDATE, CURRENT, SUPERSEDED, DUPLICATE, RETRACTED, FAILED_EXTRACTION.';
COMMENT ON COLUMN APS_CORE.CONTENT_VERSIONS.IS_CURRENT IS
    'Denormalized current flag maintained by ingestion. APS_CORE.CONTENT_ITEM_CURRENT_VERSION is the deterministic pointer used by production views.';

CREATE TABLE IF NOT EXISTS APS_CORE.CONTENT_ITEM_CURRENT_VERSION (
    CONTENT_ID VARCHAR NOT NULL,
    CURRENT_CONTENT_VERSION_ID VARCHAR NOT NULL,
    CURRENT_CONTENT_VERSION_KEY VARCHAR NOT NULL,
    SELECTED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    SELECTION_REASON VARCHAR NOT NULL,
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CONTENT_ITEM_CURRENT_VERSION PRIMARY KEY (CONTENT_ID),
    CONSTRAINT FK_CURRENT_VERSION_ITEM FOREIGN KEY (CONTENT_ID)
        REFERENCES APS_CORE.CONTENT_ITEMS (CONTENT_ID),
    CONSTRAINT FK_CURRENT_VERSION_VERSION FOREIGN KEY (CURRENT_CONTENT_VERSION_ID)
        REFERENCES APS_CORE.CONTENT_VERSIONS (CONTENT_VERSION_ID)
);

COMMENT ON TABLE APS_CORE.CONTENT_ITEM_CURRENT_VERSION IS
    'One-row-per-content-item pointer to the current version. Use this table rather than trusting IS_CURRENT alone.';
COMMENT ON COLUMN APS_CORE.CONTENT_ITEM_CURRENT_VERSION.SELECTION_REASON IS
    'Why this version became current, for example INITIAL_INGEST, NEW_SOURCE_REVISION, RECONCILED_MOVE, MANUAL_OVERRIDE.';

CREATE TABLE IF NOT EXISTS APS_CORE.CONTENT_BODIES (
    CONTENT_BODY_ID VARCHAR NOT NULL,
    CONTENT_ID VARCHAR NOT NULL,
    CONTENT_VERSION_ID VARCHAR NOT NULL,
    CONTENT_BODY_KEY VARCHAR NOT NULL,
    PARENT_CONTENT_BODY_ID VARCHAR,
    BODY_ROLE VARCHAR NOT NULL,
    BODY_FORMAT VARCHAR NOT NULL,
    BODY_TEXT VARCHAR,
    BODY_LOCATION VARCHAR,
    SECTION_PATH VARCHAR,
    SECTION_TITLE VARCHAR,
    SECTION_LEVEL NUMBER(38, 0),
    SECTION_ORDER NUMBER(38, 0),
    ANCHOR_START NUMBER(38, 0),
    ANCHOR_END NUMBER(38, 0),
    IS_PRIMARY_BODY BOOLEAN NOT NULL DEFAULT FALSE,
    BODY_HASH VARCHAR,
    NORMALIZED_BODY_HASH VARCHAR,
    LANGUAGE_CODE VARCHAR,
    TOKEN_COUNT NUMBER(38, 0),
    EXTRACTION_METHOD VARCHAR,
    EXTRACTION_CONFIDENCE FLOAT,
    METADATA VARIANT,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CONTENT_BODIES PRIMARY KEY (CONTENT_BODY_ID),
    CONSTRAINT UK_CONTENT_BODIES_BODY_KEY UNIQUE (CONTENT_BODY_KEY),
    CONSTRAINT FK_CONTENT_BODIES_ITEM FOREIGN KEY (CONTENT_ID)
        REFERENCES APS_CORE.CONTENT_ITEMS (CONTENT_ID),
    CONSTRAINT FK_CONTENT_BODIES_VERSION FOREIGN KEY (CONTENT_VERSION_ID)
        REFERENCES APS_CORE.CONTENT_VERSIONS (CONTENT_VERSION_ID),
    CONSTRAINT FK_CONTENT_BODIES_PARENT FOREIGN KEY (PARENT_CONTENT_BODY_ID)
        REFERENCES APS_CORE.CONTENT_BODIES (CONTENT_BODY_ID)
);

COMMENT ON TABLE APS_CORE.CONTENT_BODIES IS
    'Normalized full text, markdown, HTML, OCR text, transcripts, sections, and body hashes for content versions.';
COMMENT ON COLUMN APS_CORE.CONTENT_BODIES.CONTENT_BODY_KEY IS
    'Adapter-produced merge key for a body or section. Recommended shape: CONTENT_VERSION_KEY + body role + section path + body hash.';
COMMENT ON COLUMN APS_CORE.CONTENT_BODIES.BODY_ROLE IS
    'Role of this body row, for example PRIMARY, NORMALIZED_TEXT, FULL_TEXT, SECTION, OCR_TEXT, TRANSCRIPT, SUMMARY_DERIVED.';
COMMENT ON COLUMN APS_CORE.CONTENT_BODIES.IS_PRIMARY_BODY IS
    'True for the one body that should be used as the document-level fallback for single-subject derivations.';
COMMENT ON COLUMN APS_CORE.CONTENT_BODIES.SECTION_PATH IS
    'Stable hierarchical section anchor such as 3, 3.1, Appendix.A, or slide:12.';

CREATE TABLE IF NOT EXISTS APS_CORE.CONTENT_ASSETS (
    CONTENT_ASSET_ID VARCHAR NOT NULL,
    CONTENT_ID VARCHAR NOT NULL,
    CONTENT_VERSION_ID VARCHAR NOT NULL,
    CONTENT_BODY_ID VARCHAR,
    CONTENT_ASSET_KEY VARCHAR NOT NULL,
    ASSET_ROLE VARCHAR NOT NULL,
    ASSET_TYPE VARCHAR NOT NULL,
    SOURCE_ASSET_URI VARCHAR,
    STORAGE_URI VARCHAR,
    FILE_NAME VARCHAR,
    MIME_TYPE VARCHAR,
    ASSET_HASH VARCHAR,
    ASSET_ORDER NUMBER(38, 0),
    BODY_ANCHOR VARCHAR,
    ALT_TEXT VARCHAR,
    CAPTION_TEXT VARCHAR,
    OCR_TEXT VARCHAR,
    CHART_DATA VARIANT,
    EXTRACTION_METHOD VARCHAR,
    EXTRACTION_STATUS VARCHAR NOT NULL DEFAULT 'UNEXTRACTED',
    EXTRACTION_CONFIDENCE FLOAT,
    METADATA VARIANT,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CONTENT_ASSETS PRIMARY KEY (CONTENT_ASSET_ID),
    CONSTRAINT UK_CONTENT_ASSETS_ASSET_KEY UNIQUE (CONTENT_ASSET_KEY),
    CONSTRAINT FK_CONTENT_ASSETS_ITEM FOREIGN KEY (CONTENT_ID)
        REFERENCES APS_CORE.CONTENT_ITEMS (CONTENT_ID),
    CONSTRAINT FK_CONTENT_ASSETS_VERSION FOREIGN KEY (CONTENT_VERSION_ID)
        REFERENCES APS_CORE.CONTENT_VERSIONS (CONTENT_VERSION_ID),
    CONSTRAINT FK_CONTENT_ASSETS_BODY FOREIGN KEY (CONTENT_BODY_ID)
        REFERENCES APS_CORE.CONTENT_BODIES (CONTENT_BODY_ID)
);

COMMENT ON TABLE APS_CORE.CONTENT_ASSETS IS
    'Linked images, embedded files, charts, screenshots, OCR/caption text, asset hashes, and anchors back to body sections.';
COMMENT ON COLUMN APS_CORE.CONTENT_ASSETS.CONTENT_ASSET_KEY IS
    'Adapter-produced merge key for an asset. Recommended shape: CONTENT_VERSION_KEY + source asset URI/path + asset hash.';
COMMENT ON COLUMN APS_CORE.CONTENT_ASSETS.ASSET_ROLE IS
    'Role of the asset, for example EMBEDDED_IMAGE, LINKED_IMAGE, CHART, TABLE_IMAGE, ATTACHMENT, SCREENSHOT.';
COMMENT ON COLUMN APS_CORE.CONTENT_ASSETS.EXTRACTION_STATUS IS
    'Extraction state for OCR/caption/chart context, for example UNEXTRACTED, EXTRACTED, FAILED, NOT_APPLICABLE.';

CREATE TABLE IF NOT EXISTS APS_CORE.CONTENT_SCOPES (
    CONTENT_SCOPE_ID VARCHAR NOT NULL,
    CONTENT_ID VARCHAR NOT NULL,
    CONTENT_VERSION_ID VARCHAR,
    CONTENT_SCOPE_KEY VARCHAR NOT NULL,
    SCOPE_TYPE VARCHAR NOT NULL,
    SCOPE_LABEL VARCHAR,
    SCOPE_ENTITY_TYPE VARCHAR,
    SCOPE_ENTITY_ID VARCHAR,
    SCOPE_ENTITY_NAME VARCHAR,
    IS_PRIMARY_SCOPE BOOLEAN NOT NULL DEFAULT FALSE,
    CONFIDENCE FLOAT,
    EVIDENCE_TEXT VARCHAR,
    EVIDENCE VARIANT,
    CLASSIFICATION_METHOD VARCHAR,
    REVIEW_STATUS VARCHAR NOT NULL DEFAULT 'UNREVIEWED',
    METADATA VARIANT,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CONTENT_SCOPES PRIMARY KEY (CONTENT_SCOPE_ID),
    CONSTRAINT UK_CONTENT_SCOPES_SCOPE_KEY UNIQUE (CONTENT_SCOPE_KEY),
    CONSTRAINT FK_CONTENT_SCOPES_ITEM FOREIGN KEY (CONTENT_ID)
        REFERENCES APS_CORE.CONTENT_ITEMS (CONTENT_ID),
    CONSTRAINT FK_CONTENT_SCOPES_VERSION FOREIGN KEY (CONTENT_VERSION_ID)
        REFERENCES APS_CORE.CONTENT_VERSIONS (CONTENT_VERSION_ID)
);

COMMENT ON TABLE APS_CORE.CONTENT_SCOPES IS
    'Intended scope of the content, such as strategy, portfolio, investment, multi-investment, unknown, or mixed.';
COMMENT ON COLUMN APS_CORE.CONTENT_SCOPES.CONTENT_SCOPE_KEY IS
    'Adapter-produced merge key for a scope classification. Recommended shape: CONTENT_VERSION_KEY + scope type + entity id/name.';
COMMENT ON COLUMN APS_CORE.CONTENT_SCOPES.SCOPE_TYPE IS
    'Scope classification, for example STRATEGY, PORTFOLIO, INVESTMENT, MULTI_INVESTMENT, MARKET, FIRM, UNKNOWN, MIXED.';

CREATE TABLE IF NOT EXISTS APS_CORE.CONTENT_ENTITY_LINKS (
    CONTENT_ENTITY_LINK_ID VARCHAR NOT NULL,
    CONTENT_ID VARCHAR NOT NULL,
    CONTENT_VERSION_ID VARCHAR,
    CONTENT_BODY_ID VARCHAR,
    CONTENT_ASSET_ID VARCHAR,
    CONTENT_ENTITY_LINK_KEY VARCHAR NOT NULL,
    ENTITY_TYPE VARCHAR NOT NULL,
    ENTITY_ID VARCHAR,
    ENTITY_NAME VARCHAR,
    MENTION_TEXT VARCHAR,
    MENTION_START NUMBER(38, 0),
    MENTION_END NUMBER(38, 0),
    MENTION_CONTEXT VARCHAR,
    LINK_ROLE VARCHAR NOT NULL DEFAULT 'MENTION',
    ANCHOR_SCOPE VARCHAR NOT NULL DEFAULT 'DOCUMENT',
    RESOLUTION_METHOD VARCHAR,
    CONFIDENCE FLOAT,
    EVIDENCE_TEXT VARCHAR,
    EVIDENCE VARIANT,
    REVIEW_STATUS VARCHAR NOT NULL DEFAULT 'UNREVIEWED',
    IS_PRIMARY_SUBJECT BOOLEAN NOT NULL DEFAULT FALSE,
    METADATA VARIANT,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CONTENT_ENTITY_LINKS PRIMARY KEY (CONTENT_ENTITY_LINK_ID),
    CONSTRAINT UK_CONTENT_ENTITY_LINKS_LINK_KEY UNIQUE (CONTENT_ENTITY_LINK_KEY),
    CONSTRAINT FK_CONTENT_ENTITY_LINKS_ITEM FOREIGN KEY (CONTENT_ID)
        REFERENCES APS_CORE.CONTENT_ITEMS (CONTENT_ID),
    CONSTRAINT FK_CONTENT_ENTITY_LINKS_VERSION FOREIGN KEY (CONTENT_VERSION_ID)
        REFERENCES APS_CORE.CONTENT_VERSIONS (CONTENT_VERSION_ID),
    CONSTRAINT FK_CONTENT_ENTITY_LINKS_BODY FOREIGN KEY (CONTENT_BODY_ID)
        REFERENCES APS_CORE.CONTENT_BODIES (CONTENT_BODY_ID),
    CONSTRAINT FK_CONTENT_ENTITY_LINKS_ASSET FOREIGN KEY (CONTENT_ASSET_ID)
        REFERENCES APS_CORE.CONTENT_ASSETS (CONTENT_ASSET_ID)
);

COMMENT ON TABLE APS_CORE.CONTENT_ENTITY_LINKS IS
    'Many-to-many links from content to investments, portfolios, strategies, companies, people, funds, topics, and other entities.';
COMMENT ON COLUMN APS_CORE.CONTENT_ENTITY_LINKS.CONTENT_ENTITY_LINK_KEY IS
    'Adapter-produced merge key for an entity link. Recommended shape: CONTENT_VERSION_KEY + entity type + entity id/name + body/asset anchor + mention span.';
COMMENT ON COLUMN APS_CORE.CONTENT_ENTITY_LINKS.ENTITY_TYPE IS
    'Resolved entity category, for example INVESTMENT, PORTFOLIO, STRATEGY, COMPANY, PERSON, FUND, TOPIC, UNKNOWN.';
COMMENT ON COLUMN APS_CORE.CONTENT_ENTITY_LINKS.LINK_ROLE IS
    'Relationship to content, for example PRIMARY_SUBJECT, DOCUMENT_SUBJECT, SECTION_SUBJECT, MENTION, COMPARABLE, AUTHOR.';
COMMENT ON COLUMN APS_CORE.CONTENT_ENTITY_LINKS.ANCHOR_SCOPE IS
    'Anchor level for the evidence, for example DOCUMENT, BODY, ASSET, BODY_SPAN.';
COMMENT ON COLUMN APS_CORE.CONTENT_ENTITY_LINKS.REVIEW_STATUS IS
    'Resolution review state, for example AUTO_ACCEPTED, APPROVED, NEEDS_REVIEW, REJECTED, UNREVIEWED.';

CREATE TABLE IF NOT EXISTS APS_CORE.CONTENT_DATES (
    CONTENT_DATE_ID VARCHAR NOT NULL,
    CONTENT_ID VARCHAR NOT NULL,
    CONTENT_VERSION_ID VARCHAR,
    CONTENT_BODY_ID VARCHAR,
    CONTENT_DATE_KEY VARCHAR NOT NULL,
    DATE_TYPE VARCHAR NOT NULL,
    DATE_ROLE VARCHAR NOT NULL DEFAULT 'CANDIDATE',
    DATE_VALUE DATE,
    TIMESTAMP_VALUE TIMESTAMP_NTZ,
    PERIOD_START_DATE DATE,
    PERIOD_END_DATE DATE,
    DATE_GRANULARITY VARCHAR,
    DATE_TEXT VARCHAR,
    DATE_SOURCE VARCHAR,
    IS_PRIMARY_CANDIDATE BOOLEAN NOT NULL DEFAULT FALSE,
    DATE_PRIORITY_OVERRIDE NUMBER(38, 0),
    CONFIDENCE FLOAT,
    EVIDENCE_TEXT VARCHAR,
    EVIDENCE VARIANT,
    INFERENCE_METHOD VARCHAR,
    REVIEW_STATUS VARCHAR NOT NULL DEFAULT 'UNREVIEWED',
    METADATA VARIANT,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CONTENT_DATES PRIMARY KEY (CONTENT_DATE_ID),
    CONSTRAINT UK_CONTENT_DATES_DATE_KEY UNIQUE (CONTENT_DATE_KEY),
    CONSTRAINT FK_CONTENT_DATES_ITEM FOREIGN KEY (CONTENT_ID)
        REFERENCES APS_CORE.CONTENT_ITEMS (CONTENT_ID),
    CONSTRAINT FK_CONTENT_DATES_VERSION FOREIGN KEY (CONTENT_VERSION_ID)
        REFERENCES APS_CORE.CONTENT_VERSIONS (CONTENT_VERSION_ID),
    CONSTRAINT FK_CONTENT_DATES_BODY FOREIGN KEY (CONTENT_BODY_ID)
        REFERENCES APS_CORE.CONTENT_BODIES (CONTENT_BODY_ID)
);

COMMENT ON TABLE APS_CORE.CONTENT_DATES IS
    'Source dates, inferred dates, meeting dates, report periods, candidate effective dates, and selected operational date inputs with evidence and confidence.';
COMMENT ON COLUMN APS_CORE.CONTENT_DATES.CONTENT_DATE_KEY IS
    'Adapter-produced merge key for a date candidate. Recommended shape: CONTENT_VERSION_KEY + date type + value/period + body anchor.';
COMMENT ON COLUMN APS_CORE.CONTENT_DATES.DATE_TYPE IS
    'Date category, for example MEETING_DATE, REPORT_PERIOD_END, REPORT_PERIOD_START, EFFECTIVE_DATE_CANDIDATE, SOURCE_MODIFIED, SOURCE_CREATED, INGESTED.';
COMMENT ON COLUMN APS_CORE.CONTENT_DATES.DATE_ROLE IS
    'Date usage role, for example CANDIDATE, SOURCE_METADATA, OPERATIONAL_CANDIDATE, EXCLUDED.';
COMMENT ON COLUMN APS_CORE.CONTENT_DATES.DATE_PRIORITY_OVERRIDE IS
    'Optional lower-is-better priority override for operational-date selection. Use only when adapter evidence beats the default tie-breaker.';
