-- APS generic content canonical model.
--
-- APS_RAW remains responsible for ingestion and lineage. These APS_CORE tables
-- preserve logical content objects without forcing them into investment-shaped
-- notes too early.

CREATE SCHEMA IF NOT EXISTS APS_CORE;

CREATE TABLE IF NOT EXISTS APS_CORE.CONTENT_ITEMS (
    CONTENT_ID VARCHAR NOT NULL,
    LOGICAL_SOURCE_KEY VARCHAR NOT NULL,
    SOURCE_SYSTEM VARCHAR NOT NULL,
    SOURCE_TYPE VARCHAR NOT NULL,
    SOURCE_SUBTYPE VARCHAR,
    SOURCE_TITLE VARCHAR,
    SOURCE_URI VARCHAR,
    SOURCE_REFERENCE VARCHAR,
    SOURCE_PROVENANCE VARIANT,
    SOURCE_CREATED_AT TIMESTAMP_NTZ,
    SOURCE_MODIFIED_AT TIMESTAMP_NTZ,
    INGESTED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CANONICAL_CONTENT_HASH VARCHAR,
    REVIEW_STATUS VARCHAR NOT NULL DEFAULT 'UNREVIEWED',
    STATUS_REASON VARCHAR,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    METADATA VARIANT,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CONTENT_ITEMS PRIMARY KEY (CONTENT_ID)
);

COMMENT ON TABLE APS_CORE.CONTENT_ITEMS IS
    'One logical source object such as a PM note, strategy note, portfolio update, markdown export, webcast, or future source.';
COMMENT ON COLUMN APS_CORE.CONTENT_ITEMS.LOGICAL_SOURCE_KEY IS
    'Stable source identity from the adapter. Use this to connect re-exports and moved files to the same logical source when possible.';
COMMENT ON COLUMN APS_CORE.CONTENT_ITEMS.CANONICAL_CONTENT_HASH IS
    'Optional normalized fingerprint used for duplicate detection across source systems or re-exports.';
COMMENT ON COLUMN APS_CORE.CONTENT_ITEMS.REVIEW_STATUS IS
    'Human or workflow review state, for example UNREVIEWED, APPROVED, NEEDS_REVIEW, REJECTED, DUPLICATE, SUPERSEDED.';

CREATE TABLE IF NOT EXISTS APS_CORE.CONTENT_VERSIONS (
    CONTENT_VERSION_ID VARCHAR NOT NULL,
    CONTENT_ID VARCHAR NOT NULL,
    VERSION_NUMBER NUMBER(38, 0) NOT NULL,
    INGESTION_RUN_ID VARCHAR,
    RAW_RECORD_ID VARCHAR,
    RAW_PAYLOAD_LOCATION VARCHAR,
    NORMALIZED_PAYLOAD_LOCATION VARCHAR,
    SOURCE_EXPORT_ID VARCHAR,
    SOURCE_EXPORTED_AT TIMESTAMP_NTZ,
    SOURCE_MODIFIED_AT TIMESTAMP_NTZ,
    ADAPTER_NAME VARCHAR,
    ADAPTER_VERSION VARCHAR,
    SOURCE_FILE_HASH VARCHAR,
    BODY_HASH VARCHAR,
    ASSET_FINGERPRINT VARCHAR,
    CONTENT_FINGERPRINT VARCHAR,
    PREVIOUS_CONTENT_VERSION_ID VARCHAR,
    DUPLICATE_OF_CONTENT_VERSION_ID VARCHAR,
    DUPLICATE_REASON VARCHAR,
    VERSION_STATUS VARCHAR NOT NULL DEFAULT 'CURRENT',
    IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE,
    METADATA VARIANT,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CONTENT_VERSIONS PRIMARY KEY (CONTENT_VERSION_ID),
    CONSTRAINT FK_CONTENT_VERSIONS_ITEM FOREIGN KEY (CONTENT_ID)
        REFERENCES APS_CORE.CONTENT_ITEMS (CONTENT_ID)
);

COMMENT ON TABLE APS_CORE.CONTENT_VERSIONS IS
    'Source exports, re-exports, ingestion runs, fingerprints, duplicate detection, and version lineage for content items.';
COMMENT ON COLUMN APS_CORE.CONTENT_VERSIONS.CONTENT_FINGERPRINT IS
    'Composite fingerprint across normalized body and assets. Prefer this over URL-only dedupe.';
COMMENT ON COLUMN APS_CORE.CONTENT_VERSIONS.VERSION_STATUS IS
    'Version lifecycle state, for example CURRENT, SUPERSEDED, DUPLICATE, RETRACTED, FAILED_EXTRACTION.';

CREATE TABLE IF NOT EXISTS APS_CORE.CONTENT_BODIES (
    CONTENT_BODY_ID VARCHAR NOT NULL,
    CONTENT_VERSION_ID VARCHAR NOT NULL,
    BODY_ROLE VARCHAR NOT NULL,
    BODY_FORMAT VARCHAR NOT NULL,
    BODY_TEXT VARCHAR,
    BODY_LOCATION VARCHAR,
    SECTION_PATH VARCHAR,
    SECTION_ORDER NUMBER(38, 0),
    ANCHOR_START NUMBER(38, 0),
    ANCHOR_END NUMBER(38, 0),
    NORMALIZED_BODY_HASH VARCHAR,
    LANGUAGE_CODE VARCHAR,
    TOKEN_COUNT NUMBER(38, 0),
    EXTRACTION_METHOD VARCHAR,
    EXTRACTION_CONFIDENCE FLOAT,
    METADATA VARIANT,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CONTENT_BODIES PRIMARY KEY (CONTENT_BODY_ID),
    CONSTRAINT FK_CONTENT_BODIES_VERSION FOREIGN KEY (CONTENT_VERSION_ID)
        REFERENCES APS_CORE.CONTENT_VERSIONS (CONTENT_VERSION_ID)
);

COMMENT ON TABLE APS_CORE.CONTENT_BODIES IS
    'Normalized text, markdown, HTML, OCR text, extracted sections, and body hashes for content versions.';
COMMENT ON COLUMN APS_CORE.CONTENT_BODIES.BODY_ROLE IS
    'Role of this body row, for example NORMALIZED_TEXT, FULL_TEXT, SECTION, OCR_TEXT, TRANSCRIPT, SUMMARY_DERIVED.';
COMMENT ON COLUMN APS_CORE.CONTENT_BODIES.BODY_FORMAT IS
    'Representation format, for example TEXT, MARKDOWN, HTML, JSON, OCR_TEXT.';

CREATE TABLE IF NOT EXISTS APS_CORE.CONTENT_ASSETS (
    CONTENT_ASSET_ID VARCHAR NOT NULL,
    CONTENT_VERSION_ID VARCHAR NOT NULL,
    CONTENT_BODY_ID VARCHAR,
    ASSET_ROLE VARCHAR NOT NULL,
    ASSET_TYPE VARCHAR NOT NULL,
    SOURCE_ASSET_URI VARCHAR,
    STORAGE_URI VARCHAR,
    FILE_NAME VARCHAR,
    MIME_TYPE VARCHAR,
    ASSET_HASH VARCHAR,
    ASSET_ORDER NUMBER(38, 0),
    BODY_ANCHOR VARCHAR,
    ALT_TEXT VARCHAR,
    CAPTION_TEXT VARCHAR,
    OCR_TEXT VARCHAR,
    CHART_DATA VARIANT,
    EXTRACTION_METHOD VARCHAR,
    EXTRACTION_CONFIDENCE FLOAT,
    METADATA VARIANT,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CONTENT_ASSETS PRIMARY KEY (CONTENT_ASSET_ID),
    CONSTRAINT FK_CONTENT_ASSETS_VERSION FOREIGN KEY (CONTENT_VERSION_ID)
        REFERENCES APS_CORE.CONTENT_VERSIONS (CONTENT_VERSION_ID),
    CONSTRAINT FK_CONTENT_ASSETS_BODY FOREIGN KEY (CONTENT_BODY_ID)
        REFERENCES APS_CORE.CONTENT_BODIES (CONTENT_BODY_ID)
);

COMMENT ON TABLE APS_CORE.CONTENT_ASSETS IS
    'Linked images, embedded files, charts, screenshots, OCR/caption text, asset hashes, and anchors back to body sections.';
COMMENT ON COLUMN APS_CORE.CONTENT_ASSETS.ASSET_ROLE IS
    'Role of the asset, for example EMBEDDED_IMAGE, LINKED_IMAGE, CHART, TABLE_IMAGE, ATTACHMENT, SCREENSHOT.';

CREATE TABLE IF NOT EXISTS APS_CORE.CONTENT_SCOPES (
    CONTENT_SCOPE_ID VARCHAR NOT NULL,
    CONTENT_ID VARCHAR NOT NULL,
    CONTENT_VERSION_ID VARCHAR,
    SCOPE_TYPE VARCHAR NOT NULL,
    SCOPE_LABEL VARCHAR,
    SCOPE_ENTITY_TYPE VARCHAR,
    SCOPE_ENTITY_ID VARCHAR,
    SCOPE_ENTITY_NAME VARCHAR,
    IS_PRIMARY_SCOPE BOOLEAN NOT NULL DEFAULT FALSE,
    CONFIDENCE FLOAT,
    EVIDENCE_TEXT VARCHAR,
    EVIDENCE VARIANT,
    CLASSIFICATION_METHOD VARCHAR,
    REVIEW_STATUS VARCHAR NOT NULL DEFAULT 'UNREVIEWED',
    METADATA VARIANT,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CONTENT_SCOPES PRIMARY KEY (CONTENT_SCOPE_ID),
    CONSTRAINT FK_CONTENT_SCOPES_ITEM FOREIGN KEY (CONTENT_ID)
        REFERENCES APS_CORE.CONTENT_ITEMS (CONTENT_ID),
    CONSTRAINT FK_CONTENT_SCOPES_VERSION FOREIGN KEY (CONTENT_VERSION_ID)
        REFERENCES APS_CORE.CONTENT_VERSIONS (CONTENT_VERSION_ID)
);

COMMENT ON TABLE APS_CORE.CONTENT_SCOPES IS
    'Intended scope of the content, such as strategy, portfolio, investment, multi-investment, unknown, or mixed.';
COMMENT ON COLUMN APS_CORE.CONTENT_SCOPES.SCOPE_TYPE IS
    'Scope classification, for example STRATEGY, PORTFOLIO, INVESTMENT, MULTI_INVESTMENT, MARKET, FIRM, UNKNOWN, MIXED.';

CREATE TABLE IF NOT EXISTS APS_CORE.CONTENT_ENTITY_LINKS (
    CONTENT_ENTITY_LINK_ID VARCHAR NOT NULL,
    CONTENT_ID VARCHAR NOT NULL,
    CONTENT_VERSION_ID VARCHAR,
    CONTENT_BODY_ID VARCHAR,
    CONTENT_ASSET_ID VARCHAR,
    ENTITY_TYPE VARCHAR NOT NULL,
    ENTITY_ID VARCHAR,
    ENTITY_NAME VARCHAR,
    MENTION_TEXT VARCHAR,
    MENTION_CONTEXT VARCHAR,
    LINK_ROLE VARCHAR NOT NULL DEFAULT 'MENTION',
    RESOLUTION_METHOD VARCHAR,
    CONFIDENCE FLOAT,
    EVIDENCE_TEXT VARCHAR,
    EVIDENCE VARIANT,
    REVIEW_STATUS VARCHAR NOT NULL DEFAULT 'UNREVIEWED',
    IS_PRIMARY_SUBJECT BOOLEAN NOT NULL DEFAULT FALSE,
    METADATA VARIANT,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CONTENT_ENTITY_LINKS PRIMARY KEY (CONTENT_ENTITY_LINK_ID),
    CONSTRAINT FK_CONTENT_ENTITY_LINKS_ITEM FOREIGN KEY (CONTENT_ID)
        REFERENCES APS_CORE.CONTENT_ITEMS (CONTENT_ID),
    CONSTRAINT FK_CONTENT_ENTITY_LINKS_VERSION FOREIGN KEY (CONTENT_VERSION_ID)
        REFERENCES APS_CORE.CONTENT_VERSIONS (CONTENT_VERSION_ID),
    CONSTRAINT FK_CONTENT_ENTITY_LINKS_BODY FOREIGN KEY (CONTENT_BODY_ID)
        REFERENCES APS_CORE.CONTENT_BODIES (CONTENT_BODY_ID),
    CONSTRAINT FK_CONTENT_ENTITY_LINKS_ASSET FOREIGN KEY (CONTENT_ASSET_ID)
        REFERENCES APS_CORE.CONTENT_ASSETS (CONTENT_ASSET_ID)
);

COMMENT ON TABLE APS_CORE.CONTENT_ENTITY_LINKS IS
    'Many-to-many links from content to investments, portfolios, strategies, companies, people, funds, topics, and other entities.';
COMMENT ON COLUMN APS_CORE.CONTENT_ENTITY_LINKS.ENTITY_TYPE IS
    'Resolved entity category, for example INVESTMENT, PORTFOLIO, STRATEGY, COMPANY, PERSON, FUND, TOPIC, UNKNOWN.';
COMMENT ON COLUMN APS_CORE.CONTENT_ENTITY_LINKS.REVIEW_STATUS IS
    'Resolution review state, for example AUTO_ACCEPTED, APPROVED, NEEDS_REVIEW, REJECTED, UNREVIEWED.';

CREATE TABLE IF NOT EXISTS APS_CORE.CONTENT_DATES (
    CONTENT_DATE_ID VARCHAR NOT NULL,
    CONTENT_ID VARCHAR NOT NULL,
    CONTENT_VERSION_ID VARCHAR,
    DATE_TYPE VARCHAR NOT NULL,
    DATE_VALUE DATE,
    TIMESTAMP_VALUE TIMESTAMP_NTZ,
    PERIOD_START_DATE DATE,
    PERIOD_END_DATE DATE,
    DATE_TEXT VARCHAR,
    DATE_SOURCE VARCHAR,
    IS_PRIMARY_CANDIDATE BOOLEAN NOT NULL DEFAULT FALSE,
    CONFIDENCE FLOAT,
    EVIDENCE_TEXT VARCHAR,
    EVIDENCE VARIANT,
    INFERENCE_METHOD VARCHAR,
    REVIEW_STATUS VARCHAR NOT NULL DEFAULT 'UNREVIEWED',
    METADATA VARIANT,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CONTENT_DATES PRIMARY KEY (CONTENT_DATE_ID),
    CONSTRAINT FK_CONTENT_DATES_ITEM FOREIGN KEY (CONTENT_ID)
        REFERENCES APS_CORE.CONTENT_ITEMS (CONTENT_ID),
    CONSTRAINT FK_CONTENT_DATES_VERSION FOREIGN KEY (CONTENT_VERSION_ID)
        REFERENCES APS_CORE.CONTENT_VERSIONS (CONTENT_VERSION_ID)
);

COMMENT ON TABLE APS_CORE.CONTENT_DATES IS
    'Source dates, inferred dates, meeting dates, report periods, and candidate effective dates with evidence and confidence.';
COMMENT ON COLUMN APS_CORE.CONTENT_DATES.DATE_TYPE IS
    'Date category, for example SOURCE_CREATED, SOURCE_MODIFIED, INGESTED, MEETING_DATE, REPORT_PERIOD_START, REPORT_PERIOD_END, EFFECTIVE_DATE_CANDIDATE.';

