-- Conservative content derivations from generic content v2.
--
-- This file creates compatibility views. It does not replace an existing
-- APS_CORE.INVESTMENT_NOTES table. The views emit app-shaped records only when
-- current-version, entity-resolution, body-anchor, and date-selection rules are
-- deterministic enough for production ingestion.

CREATE SCHEMA IF NOT EXISTS APS_CORE;

CREATE OR REPLACE VIEW APS_CORE.CONTENT_CURRENT_VERSIONS AS
SELECT
    ci.CONTENT_ID,
    ci.CONTENT_ITEM_KEY,
    ci.LOGICAL_SOURCE_KEY,
    ci.ITEM_IDENTITY_METHOD,
    ci.SOURCE_SYSTEM,
    ci.SOURCE_OBJECT_ID,
    ci.SOURCE_CONTAINER,
    ci.SOURCE_PATH,
    ci.SOURCE_URI,
    ci.SOURCE_URI_NORMALIZED,
    ci.SOURCE_REFERENCE,
    ci.SOURCE_TYPE,
    ci.SOURCE_SUBTYPE,
    ci.SOURCE_TITLE,
    ci.SOURCE_PROVENANCE,
    ci.SOURCE_CREATED_AT,
    ci.SOURCE_MODIFIED_AT,
    ci.REVIEW_STATUS AS CONTENT_REVIEW_STATUS,
    ci.STATUS_REASON AS CONTENT_STATUS_REASON,
    cv.CONTENT_VERSION_ID,
    cv.CONTENT_VERSION_KEY,
    cv.VERSION_NUMBER,
    cv.VERSION_REASON,
    cv.INGESTION_RUN_ID,
    cv.RAW_RECORD_ID,
    cv.RAW_PAYLOAD_LOCATION,
    cv.NORMALIZED_PAYLOAD_LOCATION,
    cv.SOURCE_EXPORT_ID,
    cv.SOURCE_VERSION_ID,
    cv.SOURCE_EXPORTED_AT,
    cv.SOURCE_MODIFIED_AT AS VERSION_SOURCE_MODIFIED_AT,
    cv.ADAPTER_NAME,
    cv.ADAPTER_VERSION,
    cv.SOURCE_FILE_HASH,
    cv.BODY_HASH,
    cv.ASSET_FINGERPRINT,
    cv.CONTENT_FINGERPRINT,
    cv.VERSION_STATUS,
    cv.IS_CURRENT,
    ccv.SELECTED_AT AS CURRENT_VERSION_SELECTED_AT,
    ccv.SELECTION_REASON AS CURRENT_VERSION_SELECTION_REASON
FROM APS_CORE.CONTENT_ITEM_CURRENT_VERSION ccv
JOIN APS_CORE.CONTENT_ITEMS ci
    ON ci.CONTENT_ID = ccv.CONTENT_ID
JOIN APS_CORE.CONTENT_VERSIONS cv
    ON cv.CONTENT_VERSION_ID = ccv.CURRENT_CONTENT_VERSION_ID
WHERE ci.IS_ACTIVE
  AND UPPER(cv.VERSION_STATUS) = 'CURRENT';

COMMENT ON VIEW APS_CORE.CONTENT_CURRENT_VERSIONS IS
    'Deterministic current content versions based on APS_CORE.CONTENT_ITEM_CURRENT_VERSION, not IS_CURRENT alone.';

CREATE OR REPLACE VIEW APS_CORE.CONTENT_PRIMARY_BODIES AS
SELECT
    CONTENT_ID,
    CONTENT_VERSION_ID,
    CONTENT_BODY_ID,
    CONTENT_BODY_KEY,
    BODY_ROLE,
    BODY_FORMAT,
    BODY_TEXT,
    BODY_LOCATION,
    SECTION_PATH,
    SECTION_TITLE,
    SECTION_LEVEL,
    SECTION_ORDER,
    NORMALIZED_BODY_HASH
FROM APS_CORE.CONTENT_BODIES
WHERE BODY_TEXT IS NOT NULL
  AND (
      IS_PRIMARY_BODY
      OR UPPER(BODY_ROLE) IN ('PRIMARY', 'NORMALIZED_TEXT', 'FULL_TEXT', 'TRANSCRIPT')
  )
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY CONTENT_VERSION_ID
    ORDER BY
        IFF(IS_PRIMARY_BODY, 0, 1),
        CASE UPPER(BODY_ROLE)
            WHEN 'PRIMARY' THEN 1
            WHEN 'NORMALIZED_TEXT' THEN 2
            WHEN 'FULL_TEXT' THEN 3
            WHEN 'TRANSCRIPT' THEN 4
            ELSE 9
        END,
        COALESCE(SECTION_ORDER, 999999),
        CONTENT_BODY_ID
) = 1;

COMMENT ON VIEW APS_CORE.CONTENT_PRIMARY_BODIES IS
    'One deterministic document-level fallback body per content version. Multi-subject derivations should prefer anchored section bodies instead.';

CREATE OR REPLACE VIEW APS_CORE.CONTENT_SELECTED_OPERATIONAL_DATES AS
WITH candidates AS (
    SELECT
        ccv.CONTENT_VERSION_ID AS SELECTED_FOR_CONTENT_VERSION_ID,
        cd.CONTENT_DATE_ID,
        cd.CONTENT_ID,
        cd.CONTENT_VERSION_ID AS SOURCE_CONTENT_VERSION_ID,
        cd.CONTENT_BODY_ID,
        cd.DATE_TYPE,
        cd.DATE_ROLE,
        COALESCE(cd.DATE_VALUE, CAST(cd.TIMESTAMP_VALUE AS DATE), cd.PERIOD_END_DATE, cd.PERIOD_START_DATE) AS OPERATIONAL_DATE,
        cd.TIMESTAMP_VALUE AS OPERATIONAL_TIMESTAMP,
        cd.PERIOD_START_DATE,
        cd.PERIOD_END_DATE,
        cd.DATE_TEXT,
        cd.DATE_SOURCE,
        cd.IS_PRIMARY_CANDIDATE,
        COALESCE(
            cd.DATE_PRIORITY_OVERRIDE,
            CASE UPPER(cd.DATE_TYPE)
                WHEN 'MEETING_DATE' THEN 10
                WHEN 'REPORT_PERIOD_END' THEN 20
                WHEN 'REPORT_PERIOD_START' THEN 30
                WHEN 'EFFECTIVE_DATE_CANDIDATE' THEN 40
                WHEN 'SOURCE_MODIFIED' THEN 50
                WHEN 'SOURCE_CREATED' THEN 60
                WHEN 'INGESTED' THEN 70
                ELSE 90
            END
        ) AS DATE_SELECTION_PRIORITY,
        cd.CONFIDENCE,
        cd.EVIDENCE_TEXT,
        cd.EVIDENCE,
        cd.INFERENCE_METHOD,
        cd.REVIEW_STATUS,
        cd.CREATED_AT
    FROM APS_CORE.CONTENT_DATES cd
    JOIN APS_CORE.CONTENT_CURRENT_VERSIONS ccv
        ON ccv.CONTENT_ID = cd.CONTENT_ID
       AND (cd.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID OR cd.CONTENT_VERSION_ID IS NULL)
    WHERE UPPER(cd.DATE_ROLE) <> 'EXCLUDED'
      AND COALESCE(cd.DATE_VALUE, CAST(cd.TIMESTAMP_VALUE AS DATE), cd.PERIOD_END_DATE, cd.PERIOD_START_DATE) IS NOT NULL
      AND UPPER(cd.DATE_TYPE) IN (
          'MEETING_DATE',
          'REPORT_PERIOD_END',
          'REPORT_PERIOD_START',
          'EFFECTIVE_DATE_CANDIDATE',
          'SOURCE_MODIFIED',
          'SOURCE_CREATED',
          'INGESTED'
      )
)
SELECT
    CONTENT_DATE_ID,
    CONTENT_ID,
    SELECTED_FOR_CONTENT_VERSION_ID AS CONTENT_VERSION_ID,
    SOURCE_CONTENT_VERSION_ID,
    CONTENT_BODY_ID,
    DATE_TYPE AS OPERATIONAL_DATE_TYPE,
    DATE_ROLE AS OPERATIONAL_DATE_ROLE,
    OPERATIONAL_DATE,
    OPERATIONAL_TIMESTAMP,
    PERIOD_START_DATE,
    PERIOD_END_DATE,
    DATE_TEXT,
    DATE_SOURCE,
    DATE_SELECTION_PRIORITY,
    CONFIDENCE AS OPERATIONAL_DATE_CONFIDENCE,
    EVIDENCE_TEXT AS OPERATIONAL_DATE_EVIDENCE,
    EVIDENCE AS OPERATIONAL_DATE_EVIDENCE_JSON,
    INFERENCE_METHOD AS OPERATIONAL_DATE_INFERENCE_METHOD,
    REVIEW_STATUS AS OPERATIONAL_DATE_REVIEW_STATUS
FROM candidates
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY CONTENT_ID, SELECTED_FOR_CONTENT_VERSION_ID
    ORDER BY
        IFF(SOURCE_CONTENT_VERSION_ID IS NOT NULL, 0, 1),
        IFF(IS_PRIMARY_CANDIDATE, 0, 1),
        DATE_SELECTION_PRIORITY,
        COALESCE(CONFIDENCE, 0) DESC,
        OPERATIONAL_DATE DESC,
        CREATED_AT DESC,
        CONTENT_DATE_ID
) = 1;

COMMENT ON VIEW APS_CORE.CONTENT_SELECTED_OPERATIONAL_DATES IS
    'One selected operational date per current content version using deterministic tie-breaking: version-specific dates, primary flag, date type priority, confidence, latest date, created timestamp, id.';

CREATE OR REPLACE VIEW APS_CORE.CONTENT_ENTITY_LINK_DERIVATION_CONTEXT AS
WITH approved_links AS (
    SELECT
        cel.CONTENT_ID,
        COALESCE(cel.CONTENT_VERSION_ID, ccv.CONTENT_VERSION_ID) AS CONTENT_VERSION_ID,
        COUNT_IF(UPPER(cel.ENTITY_TYPE) = 'INVESTMENT'
            AND UPPER(cel.REVIEW_STATUS) IN ('AUTO_ACCEPTED', 'APPROVED')
            AND COALESCE(cel.CONFIDENCE, 0) >= 0.85) AS APPROVED_INVESTMENT_LINKS,
        COUNT_IF(UPPER(cel.ENTITY_TYPE) IN ('PORTFOLIO', 'FUND')
            AND UPPER(cel.REVIEW_STATUS) IN ('AUTO_ACCEPTED', 'APPROVED')
            AND COALESCE(cel.CONFIDENCE, 0) >= 0.80) AS APPROVED_PORTFOLIO_LINKS,
        COUNT_IF(UPPER(cel.ENTITY_TYPE) IN ('STRATEGY', 'TOPIC')
            AND UPPER(cel.REVIEW_STATUS) IN ('AUTO_ACCEPTED', 'APPROVED')
            AND COALESCE(cel.CONFIDENCE, 0) >= 0.80) AS APPROVED_STRATEGY_LINKS
    FROM APS_CORE.CONTENT_ENTITY_LINKS cel
    JOIN APS_CORE.CONTENT_CURRENT_VERSIONS ccv
        ON ccv.CONTENT_ID = cel.CONTENT_ID
       AND (cel.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID OR cel.CONTENT_VERSION_ID IS NULL)
    GROUP BY cel.CONTENT_ID, COALESCE(cel.CONTENT_VERSION_ID, ccv.CONTENT_VERSION_ID)
),
scope_flags AS (
    SELECT
        cs.CONTENT_ID,
        COALESCE(cs.CONTENT_VERSION_ID, ccv.CONTENT_VERSION_ID) AS CONTENT_VERSION_ID,
        COUNT_IF(UPPER(cs.SCOPE_TYPE) IN ('MULTI_INVESTMENT', 'MIXED')) AS MIXED_OR_MULTI_SCOPE_COUNT,
        COUNT_IF(UPPER(cs.SCOPE_TYPE) = 'INVESTMENT') AS INVESTMENT_SCOPE_COUNT,
        COUNT_IF(UPPER(cs.SCOPE_TYPE) = 'PORTFOLIO') AS PORTFOLIO_SCOPE_COUNT,
        COUNT_IF(UPPER(cs.SCOPE_TYPE) = 'STRATEGY') AS STRATEGY_SCOPE_COUNT
    FROM APS_CORE.CONTENT_SCOPES cs
    JOIN APS_CORE.CONTENT_CURRENT_VERSIONS ccv
        ON ccv.CONTENT_ID = cs.CONTENT_ID
       AND (cs.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID OR cs.CONTENT_VERSION_ID IS NULL)
    WHERE UPPER(cs.REVIEW_STATUS) IN ('AUTO_ACCEPTED', 'APPROVED', 'UNREVIEWED')
    GROUP BY cs.CONTENT_ID, COALESCE(cs.CONTENT_VERSION_ID, ccv.CONTENT_VERSION_ID)
)
SELECT
    ccv.CONTENT_ID,
    ccv.CONTENT_VERSION_ID,
    COALESCE(al.APPROVED_INVESTMENT_LINKS, 0) AS APPROVED_INVESTMENT_LINKS,
    COALESCE(al.APPROVED_PORTFOLIO_LINKS, 0) AS APPROVED_PORTFOLIO_LINKS,
    COALESCE(al.APPROVED_STRATEGY_LINKS, 0) AS APPROVED_STRATEGY_LINKS,
    COALESCE(sf.MIXED_OR_MULTI_SCOPE_COUNT, 0) AS MIXED_OR_MULTI_SCOPE_COUNT,
    COALESCE(sf.INVESTMENT_SCOPE_COUNT, 0) AS INVESTMENT_SCOPE_COUNT,
    COALESCE(sf.PORTFOLIO_SCOPE_COUNT, 0) AS PORTFOLIO_SCOPE_COUNT,
    COALESCE(sf.STRATEGY_SCOPE_COUNT, 0) AS STRATEGY_SCOPE_COUNT,
    IFF(
        COALESCE(al.APPROVED_INVESTMENT_LINKS, 0) > 1
        OR COALESCE(sf.MIXED_OR_MULTI_SCOPE_COUNT, 0) > 0,
        TRUE,
        FALSE
    ) AS INVESTMENT_DERIVATION_REQUIRES_BODY_ANCHOR,
    IFF(
        COALESCE(al.APPROVED_PORTFOLIO_LINKS, 0) > 1
        OR COALESCE(sf.MIXED_OR_MULTI_SCOPE_COUNT, 0) > 0,
        TRUE,
        FALSE
    ) AS PORTFOLIO_DERIVATION_REQUIRES_BODY_ANCHOR,
    IFF(
        COALESCE(al.APPROVED_STRATEGY_LINKS, 0) > 1
        OR COALESCE(sf.MIXED_OR_MULTI_SCOPE_COUNT, 0) > 0,
        TRUE,
        FALSE
    ) AS STRATEGY_DERIVATION_REQUIRES_BODY_ANCHOR
FROM APS_CORE.CONTENT_CURRENT_VERSIONS ccv
LEFT JOIN approved_links al
    ON al.CONTENT_ID = ccv.CONTENT_ID
   AND al.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID
LEFT JOIN scope_flags sf
    ON sf.CONTENT_ID = ccv.CONTENT_ID
   AND sf.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID;

COMMENT ON VIEW APS_CORE.CONTENT_ENTITY_LINK_DERIVATION_CONTEXT IS
    'Per-current-version context used to decide when entity links must anchor to a section/body before deriving app-facing notes.';

CREATE OR REPLACE VIEW APS_CORE.INVESTMENT_NOTES_FROM_CONTENT AS
WITH investment_links AS (
    SELECT
        cel.CONTENT_ENTITY_LINK_ID,
        cel.CONTENT_ID,
        ccv.CONTENT_VERSION_ID,
        cel.CONTENT_BODY_ID,
        cel.ENTITY_ID AS INVESTMENT_ID,
        cel.ENTITY_NAME AS INVESTMENT_NAME,
        cel.CONFIDENCE AS ENTITY_LINK_CONFIDENCE,
        cel.EVIDENCE_TEXT AS ENTITY_LINK_EVIDENCE,
        cel.REVIEW_STATUS AS ENTITY_LINK_REVIEW_STATUS,
        cel.LINK_ROLE,
        cel.IS_PRIMARY_SUBJECT,
        ctx.INVESTMENT_DERIVATION_REQUIRES_BODY_ANCHOR
    FROM APS_CORE.CONTENT_ENTITY_LINKS cel
    JOIN APS_CORE.CONTENT_CURRENT_VERSIONS ccv
        ON ccv.CONTENT_ID = cel.CONTENT_ID
       AND (cel.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID OR cel.CONTENT_VERSION_ID IS NULL)
    JOIN APS_CORE.CONTENT_ENTITY_LINK_DERIVATION_CONTEXT ctx
        ON ctx.CONTENT_ID = ccv.CONTENT_ID
       AND ctx.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID
    WHERE UPPER(cel.ENTITY_TYPE) = 'INVESTMENT'
      AND cel.ENTITY_NAME IS NOT NULL
      AND COALESCE(cel.CONFIDENCE, 0) >= 0.85
      AND UPPER(cel.REVIEW_STATUS) IN ('AUTO_ACCEPTED', 'APPROVED')
      AND (
          cel.CONTENT_BODY_ID IS NOT NULL
          OR (
              NOT ctx.INVESTMENT_DERIVATION_REQUIRES_BODY_ANCHOR
              AND (
                  cel.IS_PRIMARY_SUBJECT
                  OR UPPER(cel.LINK_ROLE) IN ('PRIMARY_SUBJECT', 'DOCUMENT_SUBJECT')
              )
          )
      )
),
portfolio_context AS (
    SELECT
        CONTENT_ID,
        LISTAGG(DISTINCT ENTITY_NAME, ', ') WITHIN GROUP (ORDER BY ENTITY_NAME) AS PORTFOLIO_NAME
    FROM APS_CORE.CONTENT_ENTITY_LINKS
    WHERE UPPER(ENTITY_TYPE) IN ('PORTFOLIO', 'FUND')
      AND ENTITY_NAME IS NOT NULL
      AND COALESCE(CONFIDENCE, 0) >= 0.70
      AND UPPER(REVIEW_STATUS) IN ('AUTO_ACCEPTED', 'APPROVED', 'UNREVIEWED')
    GROUP BY CONTENT_ID
)
SELECT
    il.INVESTMENT_NAME,
    pc.PORTFOLIO_NAME,
    sod.OPERATIONAL_DATE AS EFFECTIVE_DATE,
    ccv.SOURCE_TYPE,
    OBJECT_CONSTRUCT_KEEP_NULL(
        'content_id', ccv.CONTENT_ID,
        'content_item_key', ccv.CONTENT_ITEM_KEY,
        'content_version_id', ccv.CONTENT_VERSION_ID,
        'content_version_key', ccv.CONTENT_VERSION_KEY,
        'content_entity_link_id', il.CONTENT_ENTITY_LINK_ID,
        'source_system', ccv.SOURCE_SYSTEM,
        'source_object_id', ccv.SOURCE_OBJECT_ID,
        'source_reference', ccv.SOURCE_REFERENCE,
        'logical_source_key', ccv.LOGICAL_SOURCE_KEY,
        'ingestion_run_id', ccv.INGESTION_RUN_ID,
        'raw_record_id', ccv.RAW_RECORD_ID,
        'adapter_name', ccv.ADAPTER_NAME,
        'adapter_version', ccv.ADAPTER_VERSION,
        'derivation_rule_version', 'investment_link_confidence_0_85_anchor_v2'
    ) AS SOURCE_PROVENANCE,
    ccv.SOURCE_URI AS SOURCE_URL,
    IFF(UPPER(ccv.SOURCE_SYSTEM) = 'SHAREPOINT', ccv.SOURCE_URI, NULL) AS SOURCE_SHAREPOINT,
    ccv.SOURCE_REFERENCE,
    LEFT(REGEXP_REPLACE(COALESCE(lb.BODY_TEXT, pb.BODY_TEXT), '[[:space:]]+', ' '), 8000) AS SUMMARY,
    COALESCE(lb.BODY_TEXT, pb.BODY_TEXT) AS NOTE_TEXT,
    ccv.CONTENT_ID AS SOURCE_CONTENT_ID,
    ccv.CONTENT_VERSION_ID AS SOURCE_CONTENT_VERSION_ID,
    il.CONTENT_ENTITY_LINK_ID AS SOURCE_ENTITY_LINK_ID,
    COALESCE(lb.CONTENT_BODY_ID, pb.CONTENT_BODY_ID) AS SOURCE_CONTENT_BODY_ID,
    il.INVESTMENT_ID,
    il.ENTITY_LINK_CONFIDENCE,
    il.ENTITY_LINK_REVIEW_STATUS,
    il.ENTITY_LINK_EVIDENCE,
    sod.CONTENT_DATE_ID AS SOURCE_CONTENT_DATE_ID,
    sod.OPERATIONAL_DATE_TYPE AS EFFECTIVE_DATE_SOURCE_TYPE,
    sod.OPERATIONAL_DATE_CONFIDENCE AS EFFECTIVE_DATE_CONFIDENCE,
    sod.OPERATIONAL_DATE_EVIDENCE AS EFFECTIVE_DATE_EVIDENCE,
    COALESCE(lb.BODY_ROLE, pb.BODY_ROLE) AS SOURCE_BODY_ROLE,
    COALESCE(lb.BODY_FORMAT, pb.BODY_FORMAT) AS SOURCE_BODY_FORMAT,
    COALESCE(lb.SECTION_PATH, pb.SECTION_PATH) AS SOURCE_SECTION_PATH,
    COALESCE(lb.SECTION_TITLE, pb.SECTION_TITLE) AS SOURCE_SECTION_TITLE,
    COALESCE(lb.NORMALIZED_BODY_HASH, pb.NORMALIZED_BODY_HASH) AS NORMALIZED_BODY_HASH,
    ccv.CONTENT_FINGERPRINT,
    CASE
        WHEN sod.OPERATIONAL_DATE IS NULL THEN 'DERIVED_HIGH_CONFIDENCE_NO_OPERATIONAL_DATE'
        WHEN il.CONTENT_BODY_ID IS NULL THEN 'DERIVED_HIGH_CONFIDENCE_DOCUMENT_LEVEL'
        ELSE 'DERIVED_HIGH_CONFIDENCE_BODY_ANCHORED'
    END AS DERIVATION_STATUS,
    'investment_link_confidence_0_85_anchor_v2' AS DERIVATION_RULE_VERSION,
    CURRENT_TIMESTAMP() AS VIEW_EVALUATED_AT
FROM investment_links il
JOIN APS_CORE.CONTENT_CURRENT_VERSIONS ccv
    ON ccv.CONTENT_ID = il.CONTENT_ID
   AND ccv.CONTENT_VERSION_ID = il.CONTENT_VERSION_ID
LEFT JOIN portfolio_context pc
    ON pc.CONTENT_ID = ccv.CONTENT_ID
LEFT JOIN APS_CORE.CONTENT_BODIES lb
    ON lb.CONTENT_BODY_ID = il.CONTENT_BODY_ID
   AND lb.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID
LEFT JOIN APS_CORE.CONTENT_PRIMARY_BODIES pb
    ON pb.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID
LEFT JOIN APS_CORE.CONTENT_SELECTED_OPERATIONAL_DATES sod
    ON sod.CONTENT_ID = ccv.CONTENT_ID
   AND sod.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID;

COMMENT ON VIEW APS_CORE.INVESTMENT_NOTES_FROM_CONTENT IS
    'Derived investment-facing notes from generic content. Multi-investment and mixed-scope content requires body-anchored entity links before derivation.';

CREATE OR REPLACE VIEW APS_CORE.INVESTMENT_NOTES_COMPAT_FROM_CONTENT AS
SELECT
    INVESTMENT_NAME,
    PORTFOLIO_NAME,
    EFFECTIVE_DATE,
    SOURCE_TYPE,
    SOURCE_PROVENANCE,
    SOURCE_URL,
    SOURCE_SHAREPOINT,
    SOURCE_REFERENCE,
    SUMMARY,
    SOURCE_CONTENT_ID,
    SOURCE_CONTENT_VERSION_ID,
    SOURCE_ENTITY_LINK_ID,
    SOURCE_CONTENT_BODY_ID,
    ENTITY_LINK_CONFIDENCE,
    EFFECTIVE_DATE_CONFIDENCE,
    DERIVATION_STATUS,
    DERIVATION_RULE_VERSION
FROM APS_CORE.INVESTMENT_NOTES_FROM_CONTENT;

COMMENT ON VIEW APS_CORE.INVESTMENT_NOTES_COMPAT_FROM_CONTENT IS
    'Compatibility projection matching the current investment-note shape while preserving traceability columns for content-derived rows.';

CREATE OR REPLACE VIEW APS_CORE.PORTFOLIO_NOTES_FROM_CONTENT AS
WITH portfolio_links AS (
    SELECT
        cel.CONTENT_ENTITY_LINK_ID,
        cel.CONTENT_ID,
        ccv.CONTENT_VERSION_ID,
        cel.CONTENT_BODY_ID,
        cel.ENTITY_ID AS PORTFOLIO_ID,
        cel.ENTITY_NAME AS PORTFOLIO_NAME,
        cel.ENTITY_TYPE AS PORTFOLIO_ENTITY_TYPE,
        cel.CONFIDENCE AS ENTITY_LINK_CONFIDENCE,
        cel.EVIDENCE_TEXT AS ENTITY_LINK_EVIDENCE,
        cel.REVIEW_STATUS AS ENTITY_LINK_REVIEW_STATUS,
        ctx.PORTFOLIO_DERIVATION_REQUIRES_BODY_ANCHOR
    FROM APS_CORE.CONTENT_ENTITY_LINKS cel
    JOIN APS_CORE.CONTENT_CURRENT_VERSIONS ccv
        ON ccv.CONTENT_ID = cel.CONTENT_ID
       AND (cel.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID OR cel.CONTENT_VERSION_ID IS NULL)
    JOIN APS_CORE.CONTENT_ENTITY_LINK_DERIVATION_CONTEXT ctx
        ON ctx.CONTENT_ID = ccv.CONTENT_ID
       AND ctx.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID
    WHERE UPPER(cel.ENTITY_TYPE) IN ('PORTFOLIO', 'FUND')
      AND cel.ENTITY_NAME IS NOT NULL
      AND COALESCE(cel.CONFIDENCE, 0) >= 0.80
      AND UPPER(cel.REVIEW_STATUS) IN ('AUTO_ACCEPTED', 'APPROVED')
      AND (
          cel.CONTENT_BODY_ID IS NOT NULL
          OR (
              NOT ctx.PORTFOLIO_DERIVATION_REQUIRES_BODY_ANCHOR
              AND (
                  cel.IS_PRIMARY_SUBJECT
                  OR UPPER(cel.LINK_ROLE) IN ('PRIMARY_SUBJECT', 'DOCUMENT_SUBJECT')
              )
          )
      )
)
SELECT
    pl.PORTFOLIO_ID,
    pl.PORTFOLIO_NAME,
    pl.PORTFOLIO_ENTITY_TYPE,
    sod.OPERATIONAL_DATE AS EFFECTIVE_DATE,
    ccv.SOURCE_TYPE,
    ccv.SOURCE_URI AS SOURCE_URL,
    IFF(UPPER(ccv.SOURCE_SYSTEM) = 'SHAREPOINT', ccv.SOURCE_URI, NULL) AS SOURCE_SHAREPOINT,
    ccv.SOURCE_REFERENCE,
    LEFT(REGEXP_REPLACE(COALESCE(lb.BODY_TEXT, pb.BODY_TEXT), '[[:space:]]+', ' '), 8000) AS SUMMARY,
    COALESCE(lb.BODY_TEXT, pb.BODY_TEXT) AS NOTE_TEXT,
    ccv.CONTENT_ID AS SOURCE_CONTENT_ID,
    ccv.CONTENT_VERSION_ID AS SOURCE_CONTENT_VERSION_ID,
    pl.CONTENT_ENTITY_LINK_ID AS SOURCE_ENTITY_LINK_ID,
    COALESCE(lb.CONTENT_BODY_ID, pb.CONTENT_BODY_ID) AS SOURCE_CONTENT_BODY_ID,
    pl.ENTITY_LINK_CONFIDENCE,
    pl.ENTITY_LINK_REVIEW_STATUS,
    sod.CONTENT_DATE_ID AS SOURCE_CONTENT_DATE_ID,
    sod.OPERATIONAL_DATE_TYPE AS EFFECTIVE_DATE_SOURCE_TYPE,
    sod.OPERATIONAL_DATE_CONFIDENCE AS EFFECTIVE_DATE_CONFIDENCE,
    CASE
        WHEN sod.OPERATIONAL_DATE IS NULL THEN 'DERIVED_PORTFOLIO_NO_OPERATIONAL_DATE'
        WHEN pl.CONTENT_BODY_ID IS NULL THEN 'DERIVED_PORTFOLIO_DOCUMENT_LEVEL'
        ELSE 'DERIVED_PORTFOLIO_BODY_ANCHORED'
    END AS DERIVATION_STATUS,
    'portfolio_link_confidence_0_80_anchor_v2' AS DERIVATION_RULE_VERSION,
    CURRENT_TIMESTAMP() AS VIEW_EVALUATED_AT
FROM portfolio_links pl
JOIN APS_CORE.CONTENT_CURRENT_VERSIONS ccv
    ON ccv.CONTENT_ID = pl.CONTENT_ID
   AND ccv.CONTENT_VERSION_ID = pl.CONTENT_VERSION_ID
LEFT JOIN APS_CORE.CONTENT_BODIES lb
    ON lb.CONTENT_BODY_ID = pl.CONTENT_BODY_ID
   AND lb.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID
LEFT JOIN APS_CORE.CONTENT_PRIMARY_BODIES pb
    ON pb.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID
LEFT JOIN APS_CORE.CONTENT_SELECTED_OPERATIONAL_DATES sod
    ON sod.CONTENT_ID = ccv.CONTENT_ID
   AND sod.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID;

COMMENT ON VIEW APS_CORE.PORTFOLIO_NOTES_FROM_CONTENT IS
    'Derived portfolio/fund-facing notes from generic content using approved portfolio or fund entity links.';

CREATE OR REPLACE VIEW APS_CORE.STRATEGY_NOTES_FROM_CONTENT AS
WITH strategy_links AS (
    SELECT
        cel.CONTENT_ENTITY_LINK_ID,
        cel.CONTENT_ID,
        ccv.CONTENT_VERSION_ID,
        cel.CONTENT_BODY_ID,
        cel.ENTITY_ID AS STRATEGY_ID,
        cel.ENTITY_NAME AS STRATEGY_NAME,
        cel.ENTITY_TYPE AS STRATEGY_ENTITY_TYPE,
        cel.CONFIDENCE AS ENTITY_LINK_CONFIDENCE,
        cel.EVIDENCE_TEXT AS ENTITY_LINK_EVIDENCE,
        cel.REVIEW_STATUS AS ENTITY_LINK_REVIEW_STATUS,
        ctx.STRATEGY_DERIVATION_REQUIRES_BODY_ANCHOR
    FROM APS_CORE.CONTENT_ENTITY_LINKS cel
    JOIN APS_CORE.CONTENT_CURRENT_VERSIONS ccv
        ON ccv.CONTENT_ID = cel.CONTENT_ID
       AND (cel.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID OR cel.CONTENT_VERSION_ID IS NULL)
    JOIN APS_CORE.CONTENT_ENTITY_LINK_DERIVATION_CONTEXT ctx
        ON ctx.CONTENT_ID = ccv.CONTENT_ID
       AND ctx.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID
    WHERE UPPER(cel.ENTITY_TYPE) IN ('STRATEGY', 'TOPIC')
      AND cel.ENTITY_NAME IS NOT NULL
      AND COALESCE(cel.CONFIDENCE, 0) >= 0.80
      AND UPPER(cel.REVIEW_STATUS) IN ('AUTO_ACCEPTED', 'APPROVED')
      AND (
          cel.CONTENT_BODY_ID IS NOT NULL
          OR (
              NOT ctx.STRATEGY_DERIVATION_REQUIRES_BODY_ANCHOR
              AND (
                  cel.IS_PRIMARY_SUBJECT
                  OR UPPER(cel.LINK_ROLE) IN ('PRIMARY_SUBJECT', 'DOCUMENT_SUBJECT')
              )
          )
      )
),
strategy_scopes_without_links AS (
    SELECT
        cs.CONTENT_SCOPE_ID,
        cs.CONTENT_ID,
        ccv.CONTENT_VERSION_ID,
        cs.SCOPE_ENTITY_ID AS STRATEGY_ID,
        COALESCE(cs.SCOPE_ENTITY_NAME, cs.SCOPE_LABEL) AS STRATEGY_NAME,
        cs.CONFIDENCE AS ENTITY_LINK_CONFIDENCE,
        cs.REVIEW_STATUS AS ENTITY_LINK_REVIEW_STATUS
    FROM APS_CORE.CONTENT_SCOPES cs
    JOIN APS_CORE.CONTENT_CURRENT_VERSIONS ccv
        ON ccv.CONTENT_ID = cs.CONTENT_ID
       AND (cs.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID OR cs.CONTENT_VERSION_ID IS NULL)
    WHERE UPPER(cs.SCOPE_TYPE) = 'STRATEGY'
      AND COALESCE(cs.SCOPE_ENTITY_NAME, cs.SCOPE_LABEL) IS NOT NULL
      AND COALESCE(cs.CONFIDENCE, 0) >= 0.80
      AND UPPER(cs.REVIEW_STATUS) IN ('AUTO_ACCEPTED', 'APPROVED')
      AND NOT EXISTS (
          SELECT 1
          FROM strategy_links sl
          WHERE sl.CONTENT_ID = cs.CONTENT_ID
            AND sl.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID
      )
)
SELECT
    sl.STRATEGY_ID,
    sl.STRATEGY_NAME,
    sl.STRATEGY_ENTITY_TYPE,
    sod.OPERATIONAL_DATE AS EFFECTIVE_DATE,
    ccv.SOURCE_TYPE,
    ccv.SOURCE_URI AS SOURCE_URL,
    IFF(UPPER(ccv.SOURCE_SYSTEM) = 'SHAREPOINT', ccv.SOURCE_URI, NULL) AS SOURCE_SHAREPOINT,
    ccv.SOURCE_REFERENCE,
    LEFT(REGEXP_REPLACE(COALESCE(lb.BODY_TEXT, pb.BODY_TEXT), '[[:space:]]+', ' '), 8000) AS SUMMARY,
    COALESCE(lb.BODY_TEXT, pb.BODY_TEXT) AS NOTE_TEXT,
    ccv.CONTENT_ID AS SOURCE_CONTENT_ID,
    ccv.CONTENT_VERSION_ID AS SOURCE_CONTENT_VERSION_ID,
    sl.CONTENT_ENTITY_LINK_ID AS SOURCE_ENTITY_LINK_ID,
    COALESCE(lb.CONTENT_BODY_ID, pb.CONTENT_BODY_ID) AS SOURCE_CONTENT_BODY_ID,
    sl.ENTITY_LINK_CONFIDENCE,
    sl.ENTITY_LINK_REVIEW_STATUS,
    sod.CONTENT_DATE_ID AS SOURCE_CONTENT_DATE_ID,
    sod.OPERATIONAL_DATE_TYPE AS EFFECTIVE_DATE_SOURCE_TYPE,
    sod.OPERATIONAL_DATE_CONFIDENCE AS EFFECTIVE_DATE_CONFIDENCE,
    CASE
        WHEN sod.OPERATIONAL_DATE IS NULL THEN 'DERIVED_STRATEGY_NO_OPERATIONAL_DATE'
        WHEN sl.CONTENT_BODY_ID IS NULL THEN 'DERIVED_STRATEGY_DOCUMENT_LEVEL'
        ELSE 'DERIVED_STRATEGY_BODY_ANCHORED'
    END AS DERIVATION_STATUS,
    'strategy_link_confidence_0_80_anchor_v2' AS DERIVATION_RULE_VERSION,
    CURRENT_TIMESTAMP() AS VIEW_EVALUATED_AT
FROM strategy_links sl
JOIN APS_CORE.CONTENT_CURRENT_VERSIONS ccv
    ON ccv.CONTENT_ID = sl.CONTENT_ID
   AND ccv.CONTENT_VERSION_ID = sl.CONTENT_VERSION_ID
LEFT JOIN APS_CORE.CONTENT_BODIES lb
    ON lb.CONTENT_BODY_ID = sl.CONTENT_BODY_ID
   AND lb.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID
LEFT JOIN APS_CORE.CONTENT_PRIMARY_BODIES pb
    ON pb.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID
LEFT JOIN APS_CORE.CONTENT_SELECTED_OPERATIONAL_DATES sod
    ON sod.CONTENT_ID = ccv.CONTENT_ID
   AND sod.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID
UNION ALL
SELECT
    sswl.STRATEGY_ID,
    sswl.STRATEGY_NAME,
    'STRATEGY_SCOPE' AS STRATEGY_ENTITY_TYPE,
    sod.OPERATIONAL_DATE AS EFFECTIVE_DATE,
    ccv.SOURCE_TYPE,
    ccv.SOURCE_URI AS SOURCE_URL,
    IFF(UPPER(ccv.SOURCE_SYSTEM) = 'SHAREPOINT', ccv.SOURCE_URI, NULL) AS SOURCE_SHAREPOINT,
    ccv.SOURCE_REFERENCE,
    LEFT(REGEXP_REPLACE(pb.BODY_TEXT, '[[:space:]]+', ' '), 8000) AS SUMMARY,
    pb.BODY_TEXT AS NOTE_TEXT,
    ccv.CONTENT_ID AS SOURCE_CONTENT_ID,
    ccv.CONTENT_VERSION_ID AS SOURCE_CONTENT_VERSION_ID,
    NULL AS SOURCE_ENTITY_LINK_ID,
    pb.CONTENT_BODY_ID AS SOURCE_CONTENT_BODY_ID,
    sswl.ENTITY_LINK_CONFIDENCE,
    sswl.ENTITY_LINK_REVIEW_STATUS,
    sod.CONTENT_DATE_ID AS SOURCE_CONTENT_DATE_ID,
    sod.OPERATIONAL_DATE_TYPE AS EFFECTIVE_DATE_SOURCE_TYPE,
    sod.OPERATIONAL_DATE_CONFIDENCE AS EFFECTIVE_DATE_CONFIDENCE,
    'DERIVED_STRATEGY_SCOPE_DOCUMENT_LEVEL' AS DERIVATION_STATUS,
    'strategy_scope_confidence_0_80_v2' AS DERIVATION_RULE_VERSION,
    CURRENT_TIMESTAMP() AS VIEW_EVALUATED_AT
FROM strategy_scopes_without_links sswl
JOIN APS_CORE.CONTENT_CURRENT_VERSIONS ccv
    ON ccv.CONTENT_ID = sswl.CONTENT_ID
   AND ccv.CONTENT_VERSION_ID = sswl.CONTENT_VERSION_ID
LEFT JOIN APS_CORE.CONTENT_PRIMARY_BODIES pb
    ON pb.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID
LEFT JOIN APS_CORE.CONTENT_SELECTED_OPERATIONAL_DATES sod
    ON sod.CONTENT_ID = ccv.CONTENT_ID
   AND sod.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID;

COMMENT ON VIEW APS_CORE.STRATEGY_NOTES_FROM_CONTENT IS
    'Derived strategy/topic-facing notes from approved strategy/topic entity links or approved strategy scopes.';
