-- Conservative investment-note derivation from generic content.
--
-- This view intentionally does not replace an existing APS_CORE.INVESTMENT_NOTES
-- table. It exposes only high-confidence investment links so downstream apps can
-- validate the derived path before adopting it.

CREATE SCHEMA IF NOT EXISTS APS_CORE;

CREATE OR REPLACE VIEW APS_CORE.INVESTMENT_NOTES_FROM_CONTENT AS
WITH investment_links AS (
    SELECT
        CONTENT_ENTITY_LINK_ID,
        CONTENT_ID,
        CONTENT_VERSION_ID,
        CONTENT_BODY_ID,
        ENTITY_ID AS INVESTMENT_ID,
        ENTITY_NAME AS INVESTMENT_NAME,
        CONFIDENCE AS ENTITY_LINK_CONFIDENCE,
        EVIDENCE_TEXT AS ENTITY_LINK_EVIDENCE,
        REVIEW_STATUS AS ENTITY_LINK_REVIEW_STATUS,
        IS_PRIMARY_SUBJECT
    FROM APS_CORE.CONTENT_ENTITY_LINKS
    WHERE UPPER(ENTITY_TYPE) = 'INVESTMENT'
      AND COALESCE(CONFIDENCE, 0) >= 0.85
      AND UPPER(REVIEW_STATUS) IN ('AUTO_ACCEPTED', 'APPROVED')
),
portfolio_links AS (
    SELECT
        CONTENT_ID,
        LISTAGG(DISTINCT ENTITY_NAME, ', ') WITHIN GROUP (ORDER BY ENTITY_NAME) AS PORTFOLIO_NAME
    FROM APS_CORE.CONTENT_ENTITY_LINKS
    WHERE UPPER(ENTITY_TYPE) IN ('PORTFOLIO', 'FUND')
      AND ENTITY_NAME IS NOT NULL
      AND COALESCE(CONFIDENCE, 0) >= 0.70
      AND UPPER(REVIEW_STATUS) IN ('AUTO_ACCEPTED', 'APPROVED', 'UNREVIEWED')
    GROUP BY CONTENT_ID
),
best_body AS (
    SELECT
        CONTENT_BODY_ID,
        CONTENT_VERSION_ID,
        BODY_TEXT,
        BODY_ROLE,
        BODY_FORMAT,
        NORMALIZED_BODY_HASH
    FROM APS_CORE.CONTENT_BODIES
    WHERE BODY_TEXT IS NOT NULL
      AND UPPER(BODY_ROLE) IN ('SUMMARY_DERIVED', 'NORMALIZED_TEXT', 'FULL_TEXT', 'SECTION', 'TRANSCRIPT')
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY CONTENT_VERSION_ID
        ORDER BY
            CASE UPPER(BODY_ROLE)
                WHEN 'SUMMARY_DERIVED' THEN 1
                WHEN 'NORMALIZED_TEXT' THEN 2
                WHEN 'FULL_TEXT' THEN 3
                WHEN 'SECTION' THEN 4
                WHEN 'TRANSCRIPT' THEN 5
                ELSE 9
            END,
            COALESCE(SECTION_ORDER, 999999)
    ) = 1
),
linked_body AS (
    SELECT
        CONTENT_BODY_ID,
        CONTENT_VERSION_ID,
        BODY_TEXT,
        BODY_ROLE,
        BODY_FORMAT,
        NORMALIZED_BODY_HASH
    FROM APS_CORE.CONTENT_BODIES
),
best_version_effective_date AS (
    SELECT
        CONTENT_ID,
        CONTENT_VERSION_ID,
        COALESCE(DATE_VALUE, CAST(TIMESTAMP_VALUE AS DATE), PERIOD_END_DATE, PERIOD_START_DATE) AS EFFECTIVE_DATE,
        DATE_TYPE AS EFFECTIVE_DATE_SOURCE_TYPE,
        CONFIDENCE AS EFFECTIVE_DATE_CONFIDENCE,
        EVIDENCE_TEXT AS EFFECTIVE_DATE_EVIDENCE
    FROM APS_CORE.CONTENT_DATES
    WHERE CONTENT_VERSION_ID IS NOT NULL
      AND COALESCE(DATE_VALUE, CAST(TIMESTAMP_VALUE AS DATE), PERIOD_END_DATE, PERIOD_START_DATE) IS NOT NULL
      AND UPPER(DATE_TYPE) IN (
          'MEETING_DATE',
          'REPORT_PERIOD_END',
          'REPORT_PERIOD_START',
          'EFFECTIVE_DATE_CANDIDATE',
          'SOURCE_MODIFIED',
          'SOURCE_CREATED',
          'INGESTED'
      )
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY CONTENT_ID, CONTENT_VERSION_ID
        ORDER BY
            IFF(IS_PRIMARY_CANDIDATE, 0, 1),
            CASE UPPER(DATE_TYPE)
                WHEN 'MEETING_DATE' THEN 1
                WHEN 'REPORT_PERIOD_END' THEN 2
                WHEN 'REPORT_PERIOD_START' THEN 3
                WHEN 'EFFECTIVE_DATE_CANDIDATE' THEN 4
                WHEN 'SOURCE_MODIFIED' THEN 5
                WHEN 'SOURCE_CREATED' THEN 6
                WHEN 'INGESTED' THEN 7
                ELSE 9
            END,
            COALESCE(CONFIDENCE, 0) DESC,
            CREATED_AT DESC
    ) = 1
),
best_content_effective_date AS (
    SELECT
        CONTENT_ID,
        COALESCE(DATE_VALUE, CAST(TIMESTAMP_VALUE AS DATE), PERIOD_END_DATE, PERIOD_START_DATE) AS EFFECTIVE_DATE,
        DATE_TYPE AS EFFECTIVE_DATE_SOURCE_TYPE,
        CONFIDENCE AS EFFECTIVE_DATE_CONFIDENCE,
        EVIDENCE_TEXT AS EFFECTIVE_DATE_EVIDENCE
    FROM APS_CORE.CONTENT_DATES
    WHERE COALESCE(DATE_VALUE, CAST(TIMESTAMP_VALUE AS DATE), PERIOD_END_DATE, PERIOD_START_DATE) IS NOT NULL
      AND CONTENT_VERSION_ID IS NULL
      AND UPPER(DATE_TYPE) IN (
          'MEETING_DATE',
          'REPORT_PERIOD_END',
          'REPORT_PERIOD_START',
          'EFFECTIVE_DATE_CANDIDATE',
          'SOURCE_MODIFIED',
          'SOURCE_CREATED',
          'INGESTED'
      )
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY CONTENT_ID
        ORDER BY
            IFF(IS_PRIMARY_CANDIDATE, 0, 1),
            CASE UPPER(DATE_TYPE)
                WHEN 'MEETING_DATE' THEN 1
                WHEN 'REPORT_PERIOD_END' THEN 2
                WHEN 'REPORT_PERIOD_START' THEN 3
                WHEN 'EFFECTIVE_DATE_CANDIDATE' THEN 4
                WHEN 'SOURCE_MODIFIED' THEN 5
                WHEN 'SOURCE_CREATED' THEN 6
                WHEN 'INGESTED' THEN 7
                ELSE 9
            END,
            COALESCE(CONFIDENCE, 0) DESC,
            CREATED_AT DESC
    ) = 1
)
SELECT
    il.INVESTMENT_NAME,
    pl.PORTFOLIO_NAME,
    COALESCE(bved.EFFECTIVE_DATE, bced.EFFECTIVE_DATE) AS EFFECTIVE_DATE,
    ci.SOURCE_TYPE,
    OBJECT_CONSTRUCT_KEEP_NULL(
        'content_id', ci.CONTENT_ID,
        'content_version_id', cv.CONTENT_VERSION_ID,
        'content_entity_link_id', il.CONTENT_ENTITY_LINK_ID,
        'source_system', ci.SOURCE_SYSTEM,
        'source_subtype', ci.SOURCE_SUBTYPE,
        'source_reference', ci.SOURCE_REFERENCE,
        'logical_source_key', ci.LOGICAL_SOURCE_KEY,
        'ingestion_run_id', cv.INGESTION_RUN_ID,
        'raw_record_id', cv.RAW_RECORD_ID,
        'adapter_name', cv.ADAPTER_NAME,
        'adapter_version', cv.ADAPTER_VERSION
    ) AS SOURCE_PROVENANCE,
    ci.SOURCE_URI AS SOURCE_URL,
    ci.SOURCE_REFERENCE,
    LEFT(REGEXP_REPLACE(COALESCE(lb.BODY_TEXT, bb.BODY_TEXT), '[[:space:]]+', ' '), 8000) AS SUMMARY,
    COALESCE(lb.BODY_TEXT, bb.BODY_TEXT) AS NOTE_TEXT,
    ci.CONTENT_ID AS SOURCE_CONTENT_ID,
    cv.CONTENT_VERSION_ID AS SOURCE_CONTENT_VERSION_ID,
    il.CONTENT_ENTITY_LINK_ID AS SOURCE_ENTITY_LINK_ID,
    il.INVESTMENT_ID,
    il.ENTITY_LINK_CONFIDENCE,
    il.ENTITY_LINK_REVIEW_STATUS,
    il.ENTITY_LINK_EVIDENCE,
    COALESCE(bved.EFFECTIVE_DATE_SOURCE_TYPE, bced.EFFECTIVE_DATE_SOURCE_TYPE) AS EFFECTIVE_DATE_SOURCE_TYPE,
    COALESCE(bved.EFFECTIVE_DATE_CONFIDENCE, bced.EFFECTIVE_DATE_CONFIDENCE) AS EFFECTIVE_DATE_CONFIDENCE,
    COALESCE(bved.EFFECTIVE_DATE_EVIDENCE, bced.EFFECTIVE_DATE_EVIDENCE) AS EFFECTIVE_DATE_EVIDENCE,
    COALESCE(lb.BODY_ROLE, bb.BODY_ROLE) AS SOURCE_BODY_ROLE,
    COALESCE(lb.BODY_FORMAT, bb.BODY_FORMAT) AS SOURCE_BODY_FORMAT,
    COALESCE(lb.NORMALIZED_BODY_HASH, bb.NORMALIZED_BODY_HASH) AS NORMALIZED_BODY_HASH,
    cv.CONTENT_FINGERPRINT,
    CASE
        WHEN COALESCE(bved.EFFECTIVE_DATE, bced.EFFECTIVE_DATE) IS NULL THEN 'DERIVED_HIGH_CONFIDENCE_NO_EFFECTIVE_DATE'
        ELSE 'DERIVED_HIGH_CONFIDENCE'
    END AS DERIVATION_STATUS,
    'investment_link_confidence_0_85_current_version_v1' AS DERIVATION_RULE_VERSION,
    CURRENT_TIMESTAMP() AS VIEW_EVALUATED_AT
FROM investment_links il
JOIN APS_CORE.CONTENT_ITEMS ci
    ON ci.CONTENT_ID = il.CONTENT_ID
JOIN APS_CORE.CONTENT_VERSIONS cv
    ON cv.CONTENT_ID = ci.CONTENT_ID
   AND (cv.CONTENT_VERSION_ID = il.CONTENT_VERSION_ID OR (il.CONTENT_VERSION_ID IS NULL AND cv.IS_CURRENT))
LEFT JOIN portfolio_links pl
    ON pl.CONTENT_ID = ci.CONTENT_ID
LEFT JOIN linked_body lb
    ON lb.CONTENT_BODY_ID = il.CONTENT_BODY_ID
   AND lb.CONTENT_VERSION_ID = cv.CONTENT_VERSION_ID
LEFT JOIN best_body bb
    ON bb.CONTENT_VERSION_ID = cv.CONTENT_VERSION_ID
LEFT JOIN best_version_effective_date bved
    ON bved.CONTENT_ID = ci.CONTENT_ID
   AND bved.CONTENT_VERSION_ID = cv.CONTENT_VERSION_ID
LEFT JOIN best_content_effective_date bced
    ON bced.CONTENT_ID = ci.CONTENT_ID
WHERE ci.IS_ACTIVE
  AND cv.IS_CURRENT
  AND UPPER(cv.VERSION_STATUS) = 'CURRENT';

COMMENT ON VIEW APS_CORE.INVESTMENT_NOTES_FROM_CONTENT IS
    'Derived investment-facing notes from generic content. Emits rows only for high-confidence approved investment entity links.';
