-- APS generic content quality and review diagnostics v2.
--
-- These views are production guardrails. They surface conditions Snowflake
-- standard-table constraints do not enforce for us, plus content-specific review
-- issues that should block or quarantine derived app records.

CREATE SCHEMA IF NOT EXISTS APS_CORE;

CREATE OR REPLACE VIEW APS_CORE.CONTENT_REVIEW_ISSUES AS
WITH current_version_counts AS (
    SELECT
        CONTENT_ID,
        COUNT_IF(IS_CURRENT AND UPPER(VERSION_STATUS) = 'CURRENT') AS CURRENT_VERSION_FLAG_COUNT,
        COUNT_IF(UPPER(VERSION_STATUS) = 'CURRENT') AS CURRENT_STATUS_COUNT
    FROM APS_CORE.CONTENT_VERSIONS
    GROUP BY CONTENT_ID
),
duplicate_item_keys AS (
    SELECT
        CONTENT_ITEM_KEY,
        COUNT(*) AS DUPLICATE_KEY_COUNT,
        ARRAY_AGG(CONTENT_ID) AS CONTENT_IDS
    FROM APS_CORE.CONTENT_ITEMS
    GROUP BY CONTENT_ITEM_KEY
    HAVING COUNT(*) > 1
),
duplicate_version_keys AS (
    SELECT
        CONTENT_VERSION_KEY,
        COUNT(*) AS DUPLICATE_KEY_COUNT,
        ARRAY_AGG(CONTENT_VERSION_ID) AS CONTENT_VERSION_IDS
    FROM APS_CORE.CONTENT_VERSIONS
    GROUP BY CONTENT_VERSION_KEY
    HAVING COUNT(*) > 1
),
pointer_counts AS (
    SELECT
        CONTENT_ID,
        COUNT(*) AS CURRENT_POINTER_COUNT
    FROM APS_CORE.CONTENT_ITEM_CURRENT_VERSION
    GROUP BY CONTENT_ID
),
duplicate_current_versions AS (
    SELECT
        CONTENT_ID,
        CONTENT_VERSION_ID,
        DUPLICATE_OF_CONTENT_VERSION_ID,
        DUPLICATE_REASON
    FROM APS_CORE.CONTENT_VERSIONS
    WHERE (IS_CURRENT OR UPPER(VERSION_STATUS) = 'CURRENT')
      AND DUPLICATE_OF_CONTENT_VERSION_ID IS NOT NULL
),
primary_body_counts AS (
    SELECT
        ccv.CONTENT_ID,
        ccv.CONTENT_VERSION_ID,
        COUNT_IF(cb.IS_PRIMARY_BODY) AS PRIMARY_BODY_COUNT,
        COUNT(cb.CONTENT_BODY_ID) AS BODY_COUNT
    FROM APS_CORE.CONTENT_CURRENT_VERSIONS ccv
    LEFT JOIN APS_CORE.CONTENT_BODIES cb
        ON cb.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID
       AND cb.BODY_TEXT IS NOT NULL
    GROUP BY ccv.CONTENT_ID, ccv.CONTENT_VERSION_ID
),
entity_link_health AS (
    SELECT
        ccv.CONTENT_ID,
        ccv.CONTENT_VERSION_ID,
        COUNT(cel.CONTENT_ENTITY_LINK_ID) AS ENTITY_LINK_COUNT,
        COUNT_IF(UPPER(cel.REVIEW_STATUS) IN ('AUTO_ACCEPTED', 'APPROVED', 'REJECTED')) AS REVIEWED_ENTITY_LINK_COUNT,
        COUNT_IF(UPPER(cel.REVIEW_STATUS) IN ('UNREVIEWED', 'NEEDS_REVIEW')) AS UNREVIEWED_ENTITY_LINK_COUNT,
        COUNT_IF(cel.ENTITY_ID IS NULL AND cel.ENTITY_NAME IS NOT NULL) AS UNRESOLVED_ENTITY_MENTION_COUNT
    FROM APS_CORE.CONTENT_CURRENT_VERSIONS ccv
    LEFT JOIN APS_CORE.CONTENT_ENTITY_LINKS cel
        ON cel.CONTENT_ID = ccv.CONTENT_ID
       AND (cel.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID OR cel.CONTENT_VERSION_ID IS NULL)
    GROUP BY ccv.CONTENT_ID, ccv.CONTENT_VERSION_ID
),
scope_health AS (
    SELECT
        ccv.CONTENT_ID,
        ccv.CONTENT_VERSION_ID,
        COUNT(cs.CONTENT_SCOPE_ID) AS SCOPE_COUNT,
        COUNT_IF(cs.IS_PRIMARY_SCOPE) AS PRIMARY_SCOPE_COUNT,
        COUNT_IF(UPPER(cs.SCOPE_TYPE) = 'MIXED') AS MIXED_SCOPE_COUNT,
        COUNT_IF(UPPER(cs.SCOPE_TYPE) = 'MULTI_INVESTMENT') AS MULTI_INVESTMENT_SCOPE_COUNT,
        COUNT_IF(UPPER(cs.SCOPE_TYPE) = 'INVESTMENT') AS INVESTMENT_SCOPE_COUNT,
        COUNT_IF(UPPER(cs.SCOPE_TYPE) = 'PORTFOLIO') AS PORTFOLIO_SCOPE_COUNT,
        COUNT_IF(UPPER(cs.SCOPE_TYPE) = 'STRATEGY') AS STRATEGY_SCOPE_COUNT
    FROM APS_CORE.CONTENT_CURRENT_VERSIONS ccv
    LEFT JOIN APS_CORE.CONTENT_SCOPES cs
        ON cs.CONTENT_ID = ccv.CONTENT_ID
       AND (cs.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID OR cs.CONTENT_VERSION_ID IS NULL)
       AND UPPER(cs.REVIEW_STATUS) IN ('AUTO_ACCEPTED', 'APPROVED', 'UNREVIEWED', 'NEEDS_REVIEW')
    GROUP BY ccv.CONTENT_ID, ccv.CONTENT_VERSION_ID
),
asset_health AS (
    SELECT
        ccv.CONTENT_ID,
        ccv.CONTENT_VERSION_ID,
        COUNT(ca.CONTENT_ASSET_ID) AS ASSET_COUNT,
        COUNT_IF(UPPER(ca.ASSET_TYPE) IN ('IMAGE', 'CHART', 'SCREENSHOT', 'TABLE_IMAGE')) AS IMAGE_LIKE_ASSET_COUNT,
        COUNT_IF(ca.OCR_TEXT IS NOT NULL OR ca.CAPTION_TEXT IS NOT NULL OR ca.CHART_DATA IS NOT NULL) AS ASSETS_WITH_EXTRACTED_CONTEXT
    FROM APS_CORE.CONTENT_CURRENT_VERSIONS ccv
    LEFT JOIN APS_CORE.CONTENT_ASSETS ca
        ON ca.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID
    GROUP BY ccv.CONTENT_ID, ccv.CONTENT_VERSION_ID
),
anchor_health AS (
    SELECT
        ctx.CONTENT_ID,
        ctx.CONTENT_VERSION_ID,
        COUNT_IF(UPPER(cel.ENTITY_TYPE) = 'INVESTMENT'
            AND COALESCE(cel.CONFIDENCE, 0) >= 0.85
            AND UPPER(cel.REVIEW_STATUS) IN ('AUTO_ACCEPTED', 'APPROVED')
            AND cel.CONTENT_BODY_ID IS NULL) AS HIGH_CONF_INVESTMENT_LINKS_WITHOUT_BODY,
        COUNT_IF(UPPER(cel.ENTITY_TYPE) IN ('PORTFOLIO', 'FUND')
            AND COALESCE(cel.CONFIDENCE, 0) >= 0.80
            AND UPPER(cel.REVIEW_STATUS) IN ('AUTO_ACCEPTED', 'APPROVED')
            AND cel.CONTENT_BODY_ID IS NULL) AS HIGH_CONF_PORTFOLIO_LINKS_WITHOUT_BODY,
        COUNT_IF(UPPER(cel.ENTITY_TYPE) IN ('STRATEGY', 'TOPIC')
            AND COALESCE(cel.CONFIDENCE, 0) >= 0.80
            AND UPPER(cel.REVIEW_STATUS) IN ('AUTO_ACCEPTED', 'APPROVED')
            AND cel.CONTENT_BODY_ID IS NULL) AS HIGH_CONF_STRATEGY_LINKS_WITHOUT_BODY
    FROM APS_CORE.CONTENT_ENTITY_LINK_DERIVATION_CONTEXT ctx
    LEFT JOIN APS_CORE.CONTENT_ENTITY_LINKS cel
        ON cel.CONTENT_ID = ctx.CONTENT_ID
       AND (cel.CONTENT_VERSION_ID = ctx.CONTENT_VERSION_ID OR cel.CONTENT_VERSION_ID IS NULL)
    GROUP BY ctx.CONTENT_ID, ctx.CONTENT_VERSION_ID
),
operational_date_health AS (
    SELECT
        ccv.CONTENT_ID,
        ccv.CONTENT_VERSION_ID,
        COUNT(sod.CONTENT_DATE_ID) AS SELECTED_OPERATIONAL_DATE_COUNT
    FROM APS_CORE.CONTENT_CURRENT_VERSIONS ccv
    LEFT JOIN APS_CORE.CONTENT_SELECTED_OPERATIONAL_DATES sod
        ON sod.CONTENT_ID = ccv.CONTENT_ID
       AND sod.CONTENT_VERSION_ID = ccv.CONTENT_VERSION_ID
    GROUP BY ccv.CONTENT_ID, ccv.CONTENT_VERSION_ID
)
SELECT
    ci.CONTENT_ID,
    NULL AS CONTENT_VERSION_ID,
    'DUPLICATE_CONTENT_ITEM_KEY' AS ISSUE_CODE,
    'P1' AS SEVERITY,
    'Multiple content items share the same CONTENT_ITEM_KEY. Item ingestion is not idempotent.' AS ISSUE_DETAIL,
    OBJECT_CONSTRUCT(
        'content_item_key', dik.CONTENT_ITEM_KEY,
        'duplicate_key_count', dik.DUPLICATE_KEY_COUNT,
        'content_ids', dik.CONTENT_IDS
    ) AS ISSUE_CONTEXT
FROM APS_CORE.CONTENT_ITEMS ci
JOIN duplicate_item_keys dik
    ON dik.CONTENT_ITEM_KEY = ci.CONTENT_ITEM_KEY

UNION ALL

SELECT
    cv.CONTENT_ID,
    cv.CONTENT_VERSION_ID,
    'DUPLICATE_CONTENT_VERSION_KEY' AS ISSUE_CODE,
    'P1' AS SEVERITY,
    'Multiple content versions share the same CONTENT_VERSION_KEY. Version ingestion is not idempotent.' AS ISSUE_DETAIL,
    OBJECT_CONSTRUCT(
        'content_version_key', dvk.CONTENT_VERSION_KEY,
        'duplicate_key_count', dvk.DUPLICATE_KEY_COUNT,
        'content_version_ids', dvk.CONTENT_VERSION_IDS
    ) AS ISSUE_CONTEXT
FROM APS_CORE.CONTENT_VERSIONS cv
JOIN duplicate_version_keys dvk
    ON dvk.CONTENT_VERSION_KEY = cv.CONTENT_VERSION_KEY

UNION ALL

SELECT
    ci.CONTENT_ID,
    NULL AS CONTENT_VERSION_ID,
    'MULTIPLE_CURRENT_VERSION_FLAGS' AS ISSUE_CODE,
    'P1' AS SEVERITY,
    'More than one CONTENT_VERSIONS row is marked current for this content item.' AS ISSUE_DETAIL,
    OBJECT_CONSTRUCT('current_version_flag_count', cvc.CURRENT_VERSION_FLAG_COUNT) AS ISSUE_CONTEXT
FROM APS_CORE.CONTENT_ITEMS ci
JOIN current_version_counts cvc
    ON cvc.CONTENT_ID = ci.CONTENT_ID
WHERE COALESCE(cvc.CURRENT_VERSION_FLAG_COUNT, 0) > 1

UNION ALL

SELECT
    ci.CONTENT_ID,
    NULL AS CONTENT_VERSION_ID,
    'MISSING_CURRENT_VERSION_POINTER' AS ISSUE_CODE,
    'P1' AS SEVERITY,
    'Content item has no row in CONTENT_ITEM_CURRENT_VERSION.' AS ISSUE_DETAIL,
    OBJECT_CONSTRUCT('current_pointer_count', COALESCE(pc.CURRENT_POINTER_COUNT, 0)) AS ISSUE_CONTEXT
FROM APS_CORE.CONTENT_ITEMS ci
LEFT JOIN pointer_counts pc
    ON pc.CONTENT_ID = ci.CONTENT_ID
WHERE ci.IS_ACTIVE
  AND COALESCE(pc.CURRENT_POINTER_COUNT, 0) = 0

UNION ALL

SELECT
    ci.CONTENT_ID,
    NULL AS CONTENT_VERSION_ID,
    'MULTIPLE_CURRENT_VERSION_POINTERS' AS ISSUE_CODE,
    'P1' AS SEVERITY,
    'Content item has more than one row in CONTENT_ITEM_CURRENT_VERSION.' AS ISSUE_DETAIL,
    OBJECT_CONSTRUCT('current_pointer_count', COALESCE(pc.CURRENT_POINTER_COUNT, 0)) AS ISSUE_CONTEXT
FROM APS_CORE.CONTENT_ITEMS ci
JOIN pointer_counts pc
    ON pc.CONTENT_ID = ci.CONTENT_ID
WHERE COALESCE(pc.CURRENT_POINTER_COUNT, 0) > 1

UNION ALL

SELECT
    dcv.CONTENT_ID,
    dcv.CONTENT_VERSION_ID,
    'DUPLICATE_VERSION_MARKED_CURRENT' AS ISSUE_CODE,
    'P1' AS SEVERITY,
    'A version marked duplicate is also marked current or has CURRENT status.' AS ISSUE_DETAIL,
    OBJECT_CONSTRUCT(
        'duplicate_of_content_version_id', dcv.DUPLICATE_OF_CONTENT_VERSION_ID,
        'duplicate_reason', dcv.DUPLICATE_REASON
    ) AS ISSUE_CONTEXT
FROM duplicate_current_versions dcv

UNION ALL

SELECT
    ccv.CONTENT_ID,
    ccv.CONTENT_VERSION_ID,
    'CURRENT_POINTER_FLAG_MISMATCH' AS ISSUE_CODE,
    'P2' AS SEVERITY,
    'CONTENT_ITEM_CURRENT_VERSION points at a current version whose IS_CURRENT flag is false.' AS ISSUE_DETAIL,
    OBJECT_CONSTRUCT(
        'content_version_id', ccv.CONTENT_VERSION_ID,
        'content_version_key', ccv.CONTENT_VERSION_KEY,
        'is_current', ccv.IS_CURRENT
    ) AS ISSUE_CONTEXT
FROM APS_CORE.CONTENT_CURRENT_VERSIONS ccv
WHERE NOT ccv.IS_CURRENT

UNION ALL

SELECT
    pbc.CONTENT_ID,
    pbc.CONTENT_VERSION_ID,
    'MISSING_PRIMARY_BODY' AS ISSUE_CODE,
    'P1' AS SEVERITY,
    'Current version has no primary body for document-level derivations.' AS ISSUE_DETAIL,
    OBJECT_CONSTRUCT('body_count', pbc.BODY_COUNT, 'primary_body_count', pbc.PRIMARY_BODY_COUNT) AS ISSUE_CONTEXT
FROM primary_body_counts pbc
WHERE COALESCE(pbc.PRIMARY_BODY_COUNT, 0) = 0

UNION ALL

SELECT
    pbc.CONTENT_ID,
    pbc.CONTENT_VERSION_ID,
    'MULTIPLE_PRIMARY_BODIES' AS ISSUE_CODE,
    'P2' AS SEVERITY,
    'Current version has multiple primary bodies. Document-level fallback is ambiguous.' AS ISSUE_DETAIL,
    OBJECT_CONSTRUCT('primary_body_count', pbc.PRIMARY_BODY_COUNT) AS ISSUE_CONTEXT
FROM primary_body_counts pbc
WHERE COALESCE(pbc.PRIMARY_BODY_COUNT, 0) > 1

UNION ALL

SELECT
    elh.CONTENT_ID,
    elh.CONTENT_VERSION_ID,
    'MISSING_REVIEWED_ENTITY_LINKS' AS ISSUE_CODE,
    'P2' AS SEVERITY,
    'Entity links exist, but none have been reviewed or auto-accepted.' AS ISSUE_DETAIL,
    OBJECT_CONSTRUCT(
        'entity_link_count', elh.ENTITY_LINK_COUNT,
        'unreviewed_entity_link_count', elh.UNREVIEWED_ENTITY_LINK_COUNT
    ) AS ISSUE_CONTEXT
FROM entity_link_health elh
WHERE COALESCE(elh.ENTITY_LINK_COUNT, 0) > 0
  AND COALESCE(elh.REVIEWED_ENTITY_LINK_COUNT, 0) = 0

UNION ALL

SELECT
    elh.CONTENT_ID,
    elh.CONTENT_VERSION_ID,
    'UNRESOLVED_ENTITY_MENTIONS' AS ISSUE_CODE,
    'P2' AS SEVERITY,
    'Entity mentions have names but no resolved entity ids.' AS ISSUE_DETAIL,
    OBJECT_CONSTRUCT('unresolved_entity_mention_count', elh.UNRESOLVED_ENTITY_MENTION_COUNT) AS ISSUE_CONTEXT
FROM entity_link_health elh
WHERE COALESCE(elh.UNRESOLVED_ENTITY_MENTION_COUNT, 0) > 0

UNION ALL

SELECT
    sh.CONTENT_ID,
    sh.CONTENT_VERSION_ID,
    'SCOPE_CONFLICT' AS ISSUE_CODE,
    'P2' AS SEVERITY,
    'Content has conflicting primary or mixed scopes that require review before broad app derivation.' AS ISSUE_DETAIL,
    OBJECT_CONSTRUCT(
        'primary_scope_count', sh.PRIMARY_SCOPE_COUNT,
        'mixed_scope_count', sh.MIXED_SCOPE_COUNT,
        'multi_investment_scope_count', sh.MULTI_INVESTMENT_SCOPE_COUNT,
        'investment_scope_count', sh.INVESTMENT_SCOPE_COUNT,
        'portfolio_scope_count', sh.PORTFOLIO_SCOPE_COUNT,
        'strategy_scope_count', sh.STRATEGY_SCOPE_COUNT
    ) AS ISSUE_CONTEXT
FROM scope_health sh
WHERE COALESCE(sh.PRIMARY_SCOPE_COUNT, 0) > 1
   OR (
       COALESCE(sh.MIXED_SCOPE_COUNT, 0) > 0
       AND (
           COALESCE(sh.INVESTMENT_SCOPE_COUNT, 0)
           + COALESCE(sh.PORTFOLIO_SCOPE_COUNT, 0)
           + COALESCE(sh.STRATEGY_SCOPE_COUNT, 0)
       ) > 0
   )

UNION ALL

SELECT
    ah.CONTENT_ID,
    ah.CONTENT_VERSION_ID,
    'IMAGE_HEAVY_NO_EXTRACTED_CONTEXT' AS ISSUE_CODE,
    'P2' AS SEVERITY,
    'Image-heavy current version has no OCR, caption, or chart extraction context.' AS ISSUE_DETAIL,
    OBJECT_CONSTRUCT(
        'image_like_asset_count', ah.IMAGE_LIKE_ASSET_COUNT,
        'assets_with_extracted_context', ah.ASSETS_WITH_EXTRACTED_CONTEXT
    ) AS ISSUE_CONTEXT
FROM asset_health ah
WHERE COALESCE(ah.IMAGE_LIKE_ASSET_COUNT, 0) >= 3
  AND COALESCE(ah.ASSETS_WITH_EXTRACTED_CONTEXT, 0) = 0

UNION ALL

SELECT
    ahh.CONTENT_ID,
    ahh.CONTENT_VERSION_ID,
    'MISSING_INVESTMENT_BODY_ANCHORS' AS ISSUE_CODE,
    'P1' AS SEVERITY,
    'Multi-investment or mixed-scope content has approved investment links without body anchors.' AS ISSUE_DETAIL,
    OBJECT_CONSTRUCT('high_conf_investment_links_without_body', ahh.HIGH_CONF_INVESTMENT_LINKS_WITHOUT_BODY) AS ISSUE_CONTEXT
FROM anchor_health ahh
JOIN APS_CORE.CONTENT_ENTITY_LINK_DERIVATION_CONTEXT ctx
    ON ctx.CONTENT_ID = ahh.CONTENT_ID
   AND ctx.CONTENT_VERSION_ID = ahh.CONTENT_VERSION_ID
WHERE ctx.INVESTMENT_DERIVATION_REQUIRES_BODY_ANCHOR
  AND COALESCE(ahh.HIGH_CONF_INVESTMENT_LINKS_WITHOUT_BODY, 0) > 0

UNION ALL

SELECT
    ahh.CONTENT_ID,
    ahh.CONTENT_VERSION_ID,
    'MISSING_PORTFOLIO_BODY_ANCHORS' AS ISSUE_CODE,
    'P2' AS SEVERITY,
    'Mixed-scope content has approved portfolio/fund links without body anchors.' AS ISSUE_DETAIL,
    OBJECT_CONSTRUCT('high_conf_portfolio_links_without_body', ahh.HIGH_CONF_PORTFOLIO_LINKS_WITHOUT_BODY) AS ISSUE_CONTEXT
FROM anchor_health ahh
JOIN APS_CORE.CONTENT_ENTITY_LINK_DERIVATION_CONTEXT ctx
    ON ctx.CONTENT_ID = ahh.CONTENT_ID
   AND ctx.CONTENT_VERSION_ID = ahh.CONTENT_VERSION_ID
WHERE ctx.PORTFOLIO_DERIVATION_REQUIRES_BODY_ANCHOR
  AND COALESCE(ahh.HIGH_CONF_PORTFOLIO_LINKS_WITHOUT_BODY, 0) > 0

UNION ALL

SELECT
    ahh.CONTENT_ID,
    ahh.CONTENT_VERSION_ID,
    'MISSING_STRATEGY_BODY_ANCHORS' AS ISSUE_CODE,
    'P2' AS SEVERITY,
    'Mixed-scope content has approved strategy/topic links without body anchors.' AS ISSUE_DETAIL,
    OBJECT_CONSTRUCT('high_conf_strategy_links_without_body', ahh.HIGH_CONF_STRATEGY_LINKS_WITHOUT_BODY) AS ISSUE_CONTEXT
FROM anchor_health ahh
JOIN APS_CORE.CONTENT_ENTITY_LINK_DERIVATION_CONTEXT ctx
    ON ctx.CONTENT_ID = ahh.CONTENT_ID
   AND ctx.CONTENT_VERSION_ID = ahh.CONTENT_VERSION_ID
WHERE ctx.STRATEGY_DERIVATION_REQUIRES_BODY_ANCHOR
  AND COALESCE(ahh.HIGH_CONF_STRATEGY_LINKS_WITHOUT_BODY, 0) > 0

UNION ALL

SELECT
    odh.CONTENT_ID,
    odh.CONTENT_VERSION_ID,
    'MISSING_OPERATIONAL_DATE' AS ISSUE_CODE,
    'P3' AS SEVERITY,
    'No selected operational date is available. Content remains valid, but timelines will show null effective dates.' AS ISSUE_DETAIL,
    OBJECT_CONSTRUCT('selected_operational_date_count', odh.SELECTED_OPERATIONAL_DATE_COUNT) AS ISSUE_CONTEXT
FROM operational_date_health odh
WHERE COALESCE(odh.SELECTED_OPERATIONAL_DATE_COUNT, 0) = 0;

COMMENT ON VIEW APS_CORE.CONTENT_REVIEW_ISSUES IS
    'One row per production-hardening issue detected in canonical content. Mart review queues aggregate this view.';
